#!/bin/sh

set -x 

FILE="cdp${1}.demul.su"

if [ $2 -eq 0 ]; then
suwind key=cdp min=$1 max=$1 < misscn_gain_cdp.demul.su > $FILE &
Xsetntr $FILE
Velan1 $FILE $1 $1 1 0.2 
else
suwind key=cdp min=$1 max=$1 < model.su > pp
Xsetntr pp
suxwigb < pp key=f2 perc=90 &
fi