#! /bin/sh

FILE=cdp1000.su # original data

x2beg=-1500
x2end=-500    

perc=100

case "$3" in
    1)
	x1beg=0.4
	x1end=2
	;;
    2)
	x1beg=3
	x1end=4.5
	;;
    3)
	x1beg=4.5
	x1end=6
	;;
esac

suxwigb < "$1" key=offset x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end perc=$perc \
title="$1" &

suxwigb < "$2" key=offset x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end perc=$perc \
title="$2" &