#! /bin/sh


set -x 

if [ $1 = "cdp1000.su" ]; then
    clip=17
elif [ $1 = "cdp1000g.su" ]; then
    clip=95    
else
    clip=95
fi


#FILE=cdp1000.su

case "$3" in
    1)
	x1beg=3
	x1end=4.5
	x2beg=-5000
	x2end=0    
	
	;;
    2)
	x1beg=3
	x1end=4.5
	x2beg=-10000
	x2end=-5000	
	;;
    3)
	x1beg=3
	x1end=4.5
	x2beg=-16000
        x2end=-11000
	;;
    4)
	x1beg=4
	x1end=6
	x2beg=-5000
	x2end=0    
	
	;;
    5)
	x1beg=4
	x1end=6
	x2beg=-10000
	x2end=-5000	
	;;
    6)
	x1beg=4
	x1end=6
	x2beg=-16000
        x2end=-11000
	;;
    7)
	x1beg=3
	x1end=5
	x2beg=-"$4"
        x2end=000
	;;
esac

suxwigb < "$1" key=offset x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end clip=$clip \
title="$1" &


suxwigb < "$2" key=offset x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end clip=$clip \
title="$2" &





