#! /bin/sh
# shell for Kirchhoff modeling for linear v(x,z)
set -x

TEMPDATA=pp
TEMPDATA2=ppp

FILE=data1.su

 nt=725 dt=0.004 ft=0.0 tmin=0.2 nxs=20 dxs=0.200 fxs=0
 fxo=-0.750 dxo=0.025 nxo=61
  fpeak=30 er=0 ls=1 
 susynlv  nt=$nt dt=$dt ft=$ft nxs=$nxs dxs=$dxs fxs=$fxs  fxo=$fxo\
  dxo=$dxo nxo=$nxo tmin=$tmin v00=2 dvdx=0.0 dvdz=0.8 dvdx=0. ob=1 \
  fpeak=$fpeak er=0 ls=0 \
    ref="1:0,0.3;4,0.3" \
    ref="1:0,0.5;0.5,0.5;2.0,1.5;3.0,1.5;4.0,1.5" \
    ref="1:2,1;2.1,1" \
    ref="1:0,0.5;1.5,2.0;4,2.0" \
    ref="1:0,3.0;0.5,3.0;2.0,2.5;4,2.5" > $TEMPDATA

    #ref="1:2,1;2.1,1" > $TEMPDATA
    
ntr=`surange < $TEMPDATA | sed 1q | sed 's/traces://'`
sushw key=ntr a=$ntr < $TEMPDATA > $TEMPDATA2
 
suchw < $TEMPDATA2 key1=cdp key2=gx key3=sx b=1 c=1 d=2 |
sushw key=d2 a=0 | 
suaddnoise sn=20 f1=4.0 f2=8.0 f3=30.0 f4=25.0 | susort cdp offset > $FILE

unif2  fx=$fxo dx=$dxo nx=$nxo v00=2 dvdx=0.0 dvdz=0.8 dvdx=0. ob=1 \
    er=0 ls=0 \
    ref="1:0,0.3;4,0.3" \
    ref="1:0,0.5;0.5,0.5;2.0,1.5;3.0,1.5;4.0,1.5" \
    ref="1:2,1;2.1,1" \
    ref="1:0,0.5;1.5,2.0;4,2.0" \
    ref="1:0,3.0;0.5,3.0;2.0,2.5;4,2.5" > vel.su
