#! /bin/sh
# Velocity analyses for the cmp gathers
# Authors: Dave Hale, Jack K. Cohen, with modifications by John Stockwell
# NOTE: Comment lines preceeding user input start with  ##
set -x

## Set parameters
velpanel="$1"
suswapbytes < ../work2/"$1" > ./"$1"

vpicks=stkvel.$velpanel
#vpicks=junk
title="$6"; # put title here 
normpow=0
slowness=0
cdpmin="$2";
cdpmax="$3"
dcdp="$4" 
fc="$5"    # This number should be around .1 or .2 for real data 
if [ -z $cdpmin ] || [ -z $cdpmax ] || [ -z $dcdp ] || [ -z $fc ] ;
then  exit 1
fi 

#cdpmin=500
#cdpmax=3000
#dcdp=500
fold=150  # only have 12 shots, otherwise would be 64/2=32 for dsx=dgx
OPTIONPS='y'  # Plotx ps contour files
OPTIONGAIN='n'
OPTIONNOISE=0    # When working with synthetic clean data add a little noise
SN=60

## Set velocity sampling and band pass filters
nv=100
dv=50.0
fv=4000.0
dxout=0.004

## set filter values
f=1,10,100,120
amps=0,1,1,0

## number of contours in contour plot
nc=20


### Get header info
nout=`sugethw key=ns <$velpanel | sed 1q | sed 's/.*ns=//'`
dt=`sugethw key=dt <$velpanel | sed 1q | sed 's/.*dt=//'`
dxout=`bc -l <<END
	$dt / 1000000
END`

echo $nout
echo $dt
echo $dxout


### Do the velocity analyses.
echo
echo
echo
echo
echo "            Instructions for Velocity Analysis."
echo
echo "  A contour semblance map will appear on the left of your screen."
echo "  A wiggle trace plot of the cdp panel being analysed will appear"
echo "  on the right as a aid in picking."
echo
echo "  Pick velocities by placing cursor on each peak in the"
echo "  semblance plot and typing 's'. Type 'q' when last peak is picked."
echo "  Note, this is 'blind' picking. You will not see any indication"
echo "  on the contour plot that a point has been picked."
echo
echo "  There will be a maximum of 4 peaks to be picked, as this is the"
echo "  number of reflectors in the model. However, for the far-offset"
echo "  CDP gathers, it may be difficult to pick all 4 peaks."
echo
echo "  A graph of the velocity function will appear, and a prompt to" 
echo "  hit the return key will be seen in this terminal window. You"
echo "  will be asked if your picks are ok. This gives you a chance"
echo "  to re-pick the velocities if you do not like the velocity function"
echo "  you have obtained."



cdp=$cdpmin

echo $cdp
echo $dxout
echo $fv

while [ $cdp -le $cdpmax ]
do
	ok=false
	while [ $ok = false ]
	do
		echo "Starting velocity analysis for cdp $cdp"
		case $OPTIONGAIN in
		y*)
		suwind < $velpanel key=cdp min=$cdp max=$cdp count=$fold |
		sugain tpow=2.0 > panel.$cdp
                ;;
                n*)
		suwind < $velpanel key=cdp min=$cdp max=$cdp  count=$fold  > panel.$cdp
		;;
                esac

		if [ $OPTIONNOISE -eq 1 ]
		then 
		suaddnoise sn=$SN < panel.$cdp > pp; cp pp panel.$cdp
		fi

		suxwigb < panel.$cdp key=offset title="CDP gather for cdp=$cdp"                xbox=700 mpicks=mpicks.$cdp  wbox=550 hbox=650 perc=99 &

       		sufilter f=$f amps=$amps < panel.$cdp |
		suvelan nv=$nv dv=$dv fv=$fv > pp

                case $OPTIONPS in
                y*)
                supscontour < pp nc=$nc bclip=0.2 wclip=0.0 f2=$fv d2=$dv \
			units="semblance" fc=$fc \
			label1="Time (sec)" label2="Velocity (feet/sec)" \
			title=$title \
                        > ../ps2/$velpanel.$cdp.'ps' &
                ;;
                esac
		suxcontour < pp nc=$nc bclip=0.2 wclip=0.0 f2=$fv d2=$dv \
			units="semblance" fc=$fc \
			label1="Time (sec)" label2="Velocity (feet/sec)" \
			title="Semblance plot for CSP $cdp" mpicks=mpicks.$cdp &
		ok=true
	
	done </dev/tty
	cdp=`bc -l <<END
		$cdp + $dcdp
END`


done


set +x


### Combine the individual picks into a composite sunmo par file
echo "Editing pick files ..."
>$vpicks
echo  "cdp=" | tr -d "\012" >>$vpicks
cdp=$cdpmin
echo  "$cdp"  | tr -d "\012" >>$vpicks
cdp=`bc -l <<END
	$cdp + $dcdp
END`
while [ $cdp -le $cdpmax ]
do
	echo  ",$cdp"  | tr -d "\012" >>$vpicks
	cdp=`bc -l <<END
		$cdp + $dcdp
END`
done
echo >>$vpicks

cdp=$cdpmin
while [ $cdp -le $cdpmax ]
do
	cat par.$cdp >>$vpicks
	cdp=`bc -l <<END
		$cdp + $dcdp
END`
done


echo "sunmo par file: $vpicks is ready"


### Clean up
cdp=$cdpmin
while [ $cdp -le $cdpmax ]
do
	rm mpicks.$cdp par.$cdp
	cdp=`bc -l <<END
		$cdp + $dcdp
END`
done
rm unisam.p



















