#! /bin/sh

#supswigp < sucdps2 f1=0 f2=0 key=offset title="a" label1="time (sec)" label2="offset(m)" > p perc=99 

supswigp < sucdps2recCGLS f1=0 f2=0 key=offset title="d" label1="time (sec)" label2="offset(m)" > p perc=99 

supswigp < sucdps2recbCGLS  f1=0 f2=0 key=offset title="e" label1="time (sec)" label2="offset(m)" > pp perc=99

#supswigp < sucdps2radcgcm f1=0 f2=0 key=f2 title="b" label1="tau (sec)" label2="q(s/m^2)" perc=99 > ppp

#supswigp < sucdps2radT f1=0 f2=0 key=f2 title="c" label1="tau (sec)" label2="q(s/m^2)" perc=99 > pppp



FILE=broch2b.ps

#psmerge in=p  in=ppp in=pppp scale=0.5,0.5 translate=2,5  translate=0,0 translate=4,0 > ~/ps/$FILE

psmerge in=p in=pp scale=.7,.7 translate=8,0 translate=8,5  rotate=90  > ~/ps/$FILE

#psmerge in=p in=pp scale=.6,.6 translate=-1,5 translate=4,5 > ~/ps/$FILE

gv ~/ps/$FILE &








