#! /bin/sh
# Convert feet to meters for FK interpolation paper 
# Daniel Trad- UBC Nov 1999

set -x 
name=sx1ext0.su
perc=$7


FILE1=${name}
FILE2=${name}"recFK" 
FILE3=${name}"gap" 
FILE4=${name}"radFK" 
# suchmod uses rounding rather than truncation
convertoffset="suchwmod key1=offset key2=offset b=0.3052"

# Use f2 instead of offset (f2 is float, offset is integer)
convertoffset="suchw key1=f2 key2=offset b=0.3052"


$convertoffset < $FILE1 > $FILE1'm'  
$convertoffset < $FILE2 > $FILE2'm'  
$convertoffset < $FILE3 > $FILE3'm'  
$convertoffset < $FILE4 > $FILE4'm'  










































