#!/bin/sh
set -x
#sunull nt=500 dt=0.004 ntr=100 | sushw key=offset a=-1000 b=20 | suaddevent v=1000 t0=0.05 type=lmo | suaddevent v=1800 t0=0.8 | sufilter f=8,12,75,90 | suxwigb clip=1 & 

#susynth2 nh=30 nx=3 dh=100 dx=250 fpeak=20 nt=1024 midpoint=0 vel=1500,2000,3000 tau=0.5,1,2 coef=1,-0.5,1 wave=0 avof=1.1 avop=1 avo=2,1,0 | suxwigb   &

nh=126
dh=25
filen="data_asym3"


susynth2 nh=$nh dh=$dh tau=0.5,1.2 hnear=-1550 vel=2000,2200 fpeak=20 coef=1,1 > datapp1.su

susynth2 nh=$nh dh=$dh hnear=-2000 tau=0.8,1 vel=2000,2100 fpeak=20 coef=1,0.4,1 > datapp2.su

susynth2 nh=$nh dh=$dh tau=0.9,1.3 hnear=-2000 vel=2000,2300 fpeak=20 coef=1,1 > datapp3.su

susynth2 nh=$nh dh=$dh tau=1.4,1.5 hnear=-500 vel=2400,2500 fpeak=20 coef=1,1 > datapp4.su


suop2 datapp1.su datapp2.su op=sum > pp1
suop2 datapp3.su datapp4.su op=sum > pp2
#suop2 pp1  pp2  op=sum | suaddnoise sn=100 > ${filen}".su"
suop2 pp1  pp2  op=sum > ${filen}".su"

Xsetntr ${filen}".su"
suxwigb key=offset < ${filen}".su" &
sustack key=cdp < ${filen}".su" > pp
suxwigb key=offset < pp wbox=200 xbox=600 &

#sunmo key=cdp vnmo=3000 < ${filen}".su" | sustack key=cdp > pp
accept=-1500,-1250,-1000,-750,-500,-250,0,250,500,750,1000,1250,1500
#accept=-1500,-1000,-500,0,500,1000,1500
suwind accept=$accept min=0 max=0 key=offset < ${filen}".su"  > ppp

#suwind accept=$accept min=0 max=0 key=offset < ${filen}".su" > ppp
#suwind j=3 key=offset < ${filen}".su" > ppp




Xsetntr ppp
suxwigb key=offset < ppp &
sustack key=cdp < ppp > pp
suxwigb key=offset < pp wbox=200 xbox=600 &
#cp  datapp1.su ${filen}".su"
rm datapp1.su datapp2.su datapp3.su datapp4.su pp1 pp2
cp ppp ${filen}"_sparse.su"
rm pp ppp 

#suwind < ${filen}".su" key=offset reject=-1000,-1050 >  ${filen}"gap.su"
#suwind < ${filen}"gap.su" key=offset min=100 abs=1 >  ${filen}"gap2.su"

#suwind < ${filen}".su" key=offset reject=-1000,-1050  >  ${filen}"gap.su"
#suwind < ${filen}"gap.su" key=offset min=100 abs=1 >  ${filen}"gap2.su"


#Xsetntr  ${filen}"gap2.su"

#suxwigb key=offset < ${filen}"gap2.su" &

exit 0
