#! /bin/sh
# Run GBmod with Xwindow Graphics
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL Xdemo
#------------------------------------------------
# Modified: Daniel Trad.

datadir=.
modelfile=${datadir}model.data

##### Build syncline model (Figure 14)

trimodel xmin=-1 zmin=0 xmax=5.0 zmax=2.0 \
1	xedge=-1,0,1,2,3,4,5 \
	zedge=0,0,0,0,0,0,0 \
	sedge=0,0,0,0,0,0,0 \
2       xedge=-1,0,0.5,1.0,1.5,2,2.5,3,4,5 \
        zedge=1,1.1,1.2,1.5,1.7,1.5,1.2,1.1,1,1  \
        sedge=0,0,0,0,0,0,0,0,0,0 \
3       xedge=-1,0,0.5,1.0,1.5,2,2.5,3,4,5 \
        zedge=1.9,1.9,1.9,1.9,1.9,1.9,1.9,1.9,1.9,1.9  \
        sedge=0,0,0,0,0,0,0,0,0,0 \
4	xedge=-1,0,1,2,3,4,5 \
	zedge=2,2,2,2,2,2,2 \
	sedge=0,0,0,0,0,0,0 \
	sfill=1,0.5,0,0,0.25,0,0 \
	sfill=1,1.8,0,0,0.1,0,0 \
	kedge=1,2,3,4 \
	> $modelfile

sxplot < $modelfile -geom 650x300+670+0 \
        label1="Depth (km)" label2="Distance (km)" \
	tricolor=none title="Syncline Model"&

#### Shoot rays (Figure 14)


rayendsfile=${datadir}rayends.data
rayfile=${datadir}rays.data

nangle=130 fangle=-65 langle=65 nxz=201 x=1.5

####   shoot the rays 1
triray <$modelfile >$rayendsfile'1' xs=1.5 zs=0 \
	rayfile=$rayfile krecord=1 nxz=$nxz \
       	nangle=130 fangle=-65 langle=65 prim=1 \
         refseq=3,1  refseq=2,0 refseq=1,-1 

xgraph <$rayfile -geom 650x300+650+330 nplot=`cat outpar` n=$nxz \
        x1beg=0 x1end=2 x2beg=-1.0 x2end=5 style=seismic linecolor=7 \
        label1="Depth (km)" label2="Distance (km)" title="Raypaths" &
####   shoot the rays 2
triray <$modelfile >$rayendsfile'2' xs=1.5 zs=0 \
	rayfile=$rayfile krecord=1 nxz=$nxz \
       	nangle=130 fangle=-65 langle=65 prim=1 \
         refseq=3,1  refseq=2,1 refseq=1,-1 

xgraph <$rayfile -geom 650x300+650+330 nplot=`cat outpar` n=$nxz \
        x1beg=0 x1end=2 x2beg=-1.0 x2end=5 style=seismic linecolor=7 \
        label1="Depth (km)" label2="Distance (km)" title="Raypaths" &


#### generate and plot commom shot record
gbbeam<$rayendsfile'1' \
        bw=0 xg=0,4 zg=0,0 ng=100 lscale=0.5 \
	krecord=1 fpeak=8 nt=101 dt=0.025 ft=0 > ray1

gbbeam<$rayendsfile'2' \
        bw=0 xg=0,4 zg=0,0 ng=100 lscale=0.5 \
	krecord=1 fpeak=8 nt=101 dt=0.025 ft=0 > ray2


suaddhead ns=101 < ray1 | sushw key=dt a=25000 > suray1
suaddhead ns=101 < ray2 | sushw key=dt a=25000 > suray2

suop2 suray1 suray2 op=sum > pp

suxwigb < pp  xbox=670 ybox=660 perc=100 xcur=3.0 \
        hbox=300 wbox=650\
        title="Common Shot Seismograms" \
        label1="Time (sec)" label2="Distance (km)" grid1=solid &

exit 0


xwigb   xbox=670 ybox=660 perc=100 xcur=3.0 \
        n1=101 d1=0.025 f1=0 hbox=300 wbox=650\
        n2=100 d2=0.04 f2=0 title="Common Shot Seismograms" \
        label1="Time (sec)" label2="Distance (km)" grid1=solid &

