#! /bin/sh
# Xdemulradon --- Multiple attenuation with  Radon Transform.
######################################################################
# Author: Daniel Trad- November 2000

# Some shortcuts for plots
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650"
HBOX=400
WBOX=350

set -x

METHOD='toep'
METHOD='HRF'
METHOD='TD'


FILE=cdp1000.su; clip=17   #clip corresponding to perc=97
FILE=cdp1000g.su; clip=95  #clip corresponding to perc=97

FILEN=$FILE
FILETEMP=pp
FILETEMP2=ppp
FILEOFF=$FILE'off'
FILERAD="${FILEN}rad_${METHOD}"
FILEMULT="${FILEN}mul_${METHOD}"
FILEPRIM="${FILEN}pri_${METHOD}"
FILERAD2="${FILEN}radmul_${METHOD}"
FILEREC=$FILEN'rec'
FILERESAMP=$FILE'resamp'

PAR="stkvel.misscn3b.su"
par=$PAR

# Options
SETNTR='n'
GETH='n'
FILT='n'
TAPER='n'
RADONFORW='y'
REMOVEMUL='y'

# PASS BAND FILTER
F=1,10,70,80
AMPS=0,1,1,0
# RADON
#***Freq############################ 

VERBOSE=1
fold=1
buffer=10; 
iter_end=4
sinc=0;
parmute=3e-9
parmute=22e-9
nq=90
under=0.999
over=1.001
qmin=-2e-9
factor=1.1

if [ $METHOD = 'HRF' ]; then
    eps1=5e-3
    eps2=5e-3
    lsmethod=1
    PROGRAM=suradonwtcgls
elif [ $METHOD = 'toep' ]; then
    eps1=5e-2
    eps2=5e-2
    lsmethod=0
    PROGRAM=suradontoep
elif [ $METHOD = 'TD' ]; then
    eps1=1e-3
    eps2=1e-3
    PROGRAM=suradontd0
    eps=0.01
    dperv=0.03;
    dperv=0.03;
    pervmin=0.5e-9;
    centralq=30
    nq=70
    perc=100
    step=0.9
    itercg=5
    iter_end=3
    smoothf=0
    smoothi=0
    testadj=0
    filtout=0
    restart=1
    LI=1
    t0=1.85
    clip=63 #clip corresponding to perc=100
    norm=1
    nw=21
    fpeak=25
    nw=0
    dtres=0.008
    ntres=875
    RESAMPLE='n'
else 
    PROGRAM=donothing
fi

scale=1.1
CDPMIN=1000
DXCDP=1
CDPMAX=1000


############################*****
perc=100

cp $FILE $FILETEMP

if [ $SETNTR = 'y' ]; then 
    Xsetntr $FILETEMP
fi

if [ $FILT = 'y' ]; then
    sufilter f=$F amps=$AMPS < $FILETEMP > $FILETEMP2;
    cp  $FILETEMP2 $FILETEMP
fi

# Save offset  for inverse radon transform
if [ $GETH = 'y' ]; then
    sugethw key=offset output=geom < $FILE > $FILEOFF    
fi

if [ $TAPER = 'y' ]; then
    sutaper < $FILETEMP > $FILETEMP2; cp $FILETEMP2 $FILETEMP
fi

if [ $RESAMPLE = 'y' ]; then
    suresamp < $FILETEMP dt=$dtres nt=$ntres > $FILETEMP2
    cp $FILETEMP2 $FILETEMP
    cp $FILETEMP2 $FILERESAMP
fi

if [ $RADONFORW = 'y' ]; then

case $PROGRAM in
suradtest*)

    suradtestfreq < $FILETEMP cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$DXCDP verbose=1 nhe=$nhe fold=$fold par=$PAR itercg=40 iter_end=$iter_end eps2=$eps2 eps1=$eps1  testadj=0 smooth=0 nq=$nq qmin=-2e-9 cdpspace=$cdpspace ntrmax=$ntrmax tmpdir='.' norm=0 lsmethod=$lsmethod nmofactor=1 smute=3 step=0.95 factor=1.5 buffer=$buffer  mute=0  parmute=$parmute offsetfile=$FILEOFF under=$under over=$over modelfile=$FILERAD keepdata=0 quantil=1  > $FILEREC
sugain scale=$scale < $FILEREC > $FILETEMP 

cp $FILETEMP $FILEREC

;;

suradontoep*)
	    
    suradontoep < $FILETEMP verbose=$verbose par=$par  eps1=$eps1  nq=$nq qmin=$qmin norm=0 \
    nmofactor=1 smute=3.0 step=0.95 factor=$factor modelfile=$FILERAD quantil=1 > $FILEREC

    $PLOTX clip=$clip < $FILEREC title="Reconstructed data from suradontoep " &
;;
suradonwtcgls*)
    
    suradonwtcgls < $FILETEMP verbose=$verbose par=$par itercg=25 iter_end=$iter_end \
    eps2=$eps2 eps1=$eps1  testadj=0  nq=$nq qmin=$qmin norm=0 nmofactor=1 smute=3.0 \
    step=0.95 factor=$factor modelfile=$FILERAD  quantil=1 > $FILEREC

;;
suradontd0*)
    suradontd0 eps1=$eps1 eps2=$eps2 iter_end=$iter_end nq=$nq itercg=$itercg eps=$eps \
    step=$step  smooth=0 testadj=$testadj verbose=$verbose par=$PAR pervmin=$pervmin \
    dperv=$dperv modelfile=$FILERAD centralq=$centralq norm=$norm nw=$nw fpeak=$fpeak \
    filtout=$filtout restart=$restart LI=$LI t0=$t0 < $FILETEMP > $FILEREC
;;
esac


fi

$PLOTR perc=$perc < $FILERAD title="Modified Radon transform"  &
$PLOTX clip=$clip < $FILEREC title="Reconstructed data from suradontoep " &


if [ $REMOVEMUL = 'y' ]; then
    Xmuterad $FILERAD $FILERAD2
    case $PROGRAM in
    suradontd0*)
    if [ $RESAMPLE = 'y' ]; then
	suradontdi0 modelfile=$FILERAD2 vgridfile="vgrid" datafile=$FILERESAMP  \
	offsetfile=$FILEOFF > $FILEMULT
	suresamp < $FILEMULT dt=0.004 nt=1751 > $FILETEMP
	cp $FILETEMP $FILEMULT
    else
	suradontdi0 modelfile=$FILERAD2 vgridfile="vgrid" datafile=$FILE  \
	offsetfile=$FILEOFF > $FILEMULT
    fi
    
    ;;
    *)
    suradon00inv $FILE $FILERAD2 par=$par nq=$nq nmofactor=1 smute=3.0 > $FILEMULT    
    ;;
    esac
    sugain scale=$scale < $FILEMULT > $FILETEMP ; cp $FILETEMP $FILEMULT
    suop2 $FILE $FILEMULT op=diff > $FILEPRIM
    #suadapdiff $FILE $FILEMULT > $FILEPRIM

    $PLOTX clip=$clip < $FILEPRIM title="Primaries" &    
    $PLOTX clip=$clip < $FILEMULT title="Multiples" &
    Velan1 $FILEMULT 1000 1000 1 0.2 "(h)"
    Velan1 $FILEPRIM 1000 1000 1 0.2 "(g)"
fi


exit 0  


































