#! /bin/sh
# shell for interpolation
# Daniel Trad - UBC - CDSST 
set -x

HBOX=400
WBOX=350
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=90"

key=tracl

NAME=$1
MINOFFSET=-2150
DH=25
FILEIN=$NAME'.su'
FILEOUT=$NAME'.int.su'


suinterp < "${FILEIN}" | sushw key=offset a=$MINOFFSET b=$DH | sushw key=ntr a=171 > "${FILEOUT}"




