#! /bin/sh

FILE0=sumisscnyn2.1.su
FILE=sumiss2
FILE2=sumiss2aux
NTR=3843

#suswapbytes < $FILE0 > $FILE
sushw key=ntr a=3843 < $FILE |
sushw key=delrt a=0  | sushw key=d1 a=0 > pp
mv pp $FILE
#suchw key1=offset key2=offset b=-1 < $FILE > pp
#mv pp $FILE2 
#suwind key=sx min=9187 max=9187 < pp  > $FILE'.9187'



