#! /bin/sh
FILEN=marmousi

FILE1=$FILEN'_shots.su'
FILEOUT=$FILEN'.kir.depth.su'
FILEVEL=$FILEN'_vels.su'
VFILE=$FILEN'.vfile'
TRAVELTIME=$FILEN'.traveltime'

READVEL='y'
VELP='y'
RAYTR='y'
RAYTRP='y'
KIRMIG='y'

nz=101
dz=40
dt=0.004

fx=0
nx=355
dx=25

fxo=0
nxo=355
dxo=25

fzo=0
nzo=101
dzo=40

fxs=0 
nxs=70 
dxs=100

fxk=0
nxk=355
dxk=25

fzk=0
nzk=401
dzk=10



case $READVEL in
y*)
sureadvel2 < $FILEVEL > pp vfile=$VFILE nz=$nz dz=$dz nx=$nx
;;
esac

case $VELP in
y*)
ximage < $VFILE n1=$nz n2=$nx d1=$dz d2=$dx legend=1 &
;;
esac

case $RAYTR in
y*)
rayt2d vfile=$VFILE tfile=$TRAVELTIME nz=$nz dz=$dz nx=$nx dx=$dx nzo=$nzo dzo=$dzo fxo=0 nxo=$nxo dxo=$dxo fxs=0 nxs=$nxs ms=1 dxs=$dxs dt=$dt
;;
esac

case $RAYTRP in
y*)
pscube < $TRAVELTIME n1=$nzo d1=$dzo f1=$fzo n2=$nxo d2=$dxo \
	 f2=$fxo n3=$nxs d3=$dxs label1="Depth (m)" label2="Midpoint (m)" \
	 label3="Shot" d3num=1000 ybox=3 hbox=4 bclip=10 d1num=500 d2num=2000 \
	 title="Traveltime Tables"  > time.eps
gv time.eps &
;;
esac

case $KIRMIG in
y*)
sukdmig2d < $FILE1 > $FILEOUT ttfile=$TRAVELTIME fzt=$fzo nzt=$nzo dzt=$dzo  dxm=$dx ntr=100000 fxt=$fxo nxt=$nxo dxt=$dxo fs=$fxs  ns=$nxs ds=$dxs nxo=$nxo dxo=$dxo fxo=$fxk fz0=$fzk nzo=$nzk dzo=$dzk
suximage perc=90 legend=1 < $FILEOUT &
;;
esac







