#! /bin/sh
# PLOTS 
# Plot for data, primaries and multiples.
# Daniel Trad- UBC Nov 1999
  
FILE=fig0linrad.ps

# PLot model


FILEN=ozdata.25


FILE1=$FILEN'.su'
FILE2=$FILEN'.filt.su'
FILE3=$FILEN'.filt.su'
FILE4=$FILEN'.suradb'

OPTIONAGC='y'
OPTIONNUM='2'

TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"

LABEL1="time (sec)" 
LABEL2="offset(m)"
LABELR="p(s/m)"


case $OPTIONAGC in
y*)
PLOTR="supswigp f1=0 f2=0 key=f2 label1=$LABEL1 label2=$LABELR perc=95"
PLOTX="supswigp f1=0 f2=0 key=offset label1=$LABEL1 label2=$LABEL2 perc=95"
GAIN="sugain agc=1 wagc=2"
;;
n*)
PLOTR="supswigp f1=0 f2=0 key=f2 label1=$LABEL1 label2=$LABELR perc=99"
PLOTX="supswigp f1=0 f2=0 key=offset label1=$LABEL1 label2=$LABEL2 perc=99"
;;
esac


case $OPTIONAGC in
y*)
#$PLOTM < $FILE1  title=$TITLE1  > p  
$GAIN < $FILE1 | $PLOTX  title=$TITLE1  > p
#$GAIN < $FILE2 | $PLOTR  title=$TITLE2  > pp
$GAIN < $FILE2 |  $PLOTX  title=$TITLE2  > pp
$GAIN < $FILE3 | $PLOTX  title=$TITLE3  > ppp 
#$GAIN < $FILE4 | $PLOTR  title=$TITLE4  > pppp
$PLOTR < $FILE4  title=$TITLE4  > pppp

;;
n*)
$PLOTX < $FILE1  title=$TITLE1  > p  
$PLOTX < $FILE2  title=$TITLE2  > pp
$PLOTX < $FILE3  title=$TITLE3  > ppp 
$PLOTR < $FILE4  title=$TITLE4  > pppp
;;
esac

case $OPTIONNUM in
2*)
psmerge in=p in=pp scale=0.5,0.5 translate=0,5 translate=4,5 > ~/ps/$FILE
;;
3*)
psmerge in=p in=pp in=ppp  scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0  > ~/ps/$FILE
;;
4*)
psmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > ~/ps/$FILE
;;
esac

gv ~/ps/$FILE &











