#!/bin/sh
plotx="suxwigb key=offset perc=100"
set -x
name=shotpcd4
file1=${name}.su
file2=${name}s.su
file1c=${name}c.su
file2c=${name}sc.su
file1z=${name}z.su
file2z=${name}sz.su
file0a=${name}0a.su
file0b=${name}0b.su
file0=${name}ext0.su

suchw key1=offset a=1020 key2=offset b=1 < $file1 > $file2

suwind key=offset min=-1000 < $file1 > $file1c
suwind key=offset max=2000 < $file2 > $file2c

sugain scale=0 < $file1c > $file1z
sugain scale=0 < $file2c > $file2z

cat $file1c $file2z > $file0a
cat $file1z $file2c > $file0b

#suop2 $file0a $file0b > $file0
suop2 $file1c $file2c > $file0
$plotx < $file0 &



exit 0

