#! /bin/sh
# shell for muting
# Daniel Trad - UBC - CDSST 
set -x

HBOX=400
WBOX=350
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb x1beg=0 wbox=550 hbox=650 perc=99 "
PLOTT="suxwigb wbox=550 hbox=650 perc=90"
PLOTX="suxwigb key=offset wbox=550 hbox=650"


key=f2

FILEIN=$1
FILEOUT=$2

FILETEMP=pppp
FILETEMP2=ppppp

      
cp $FILEIN ${FILETEMP}
ok=false
while [ $ok = false ]
	    do
	    cp ${FILETEMP} ${FILETEMP2}
           
            echo  "Would you prefer above or below muting? (a/b)" | tr -d "\012" >/dev/tty
	    read response1
	    case $response1 in
		a*) BELOW=0 ;;
		b*) BELOW=1 ;;
	    esac

	    $PLOTR key=$key < ${FILETEMP2} title=$title  mpicks=./filempicks 
	    NMUTE=`readmute << END`

	    sumute < ${FILETEMP2} key=$key xfile=xfileb tfile=tfileb nmute=$NMUTE below=$BELOW  > ${FILETEMP}
	    $PLOTR key=$key < ${FILETEMP} title=$title &
	   
	    echo  "MUTE FINISHED? (y/n) "  | tr -d "\012" >/dev/tty
	    read response
	    case $response in
	    n*) ok=false ;;
	    *) ok=true ;;
	    esac

done </dev/tty

ntr=`surange < ${FILETEMP} | sed 1q | sed 's/traces://'`
sushw key=ntr a=$ntr < ${FILETEMP} > $FILEOUT 

#rm ${FILETEMP}







