#!/bin/sh
# Script to plot the HRT computed with shaping filter
# For paper radonsparse
# Daniel Trad - July 17 2001

FILE=fighrtfilt.ps
perc=100

FILEN="cdp${cdp}"


FILE1=adjoint.su
FILE2=modells.su
FILE3=modelfilt.su
FILE4=diff.su

supaste < modelfilt.bin head=header2 > $FILE3 ns=512
suadapdiff $FILE2 $FILE3  > diff.su

# PLot model
x1beg=0
x1end=2

LABEL1="time(sec)" 
LABEL2="q"


TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"


TITLE1="Adjoint"
TITLE2="LS_sparse"
TITLE3="HRT_filtered"
TITLE4="Difference"


PLOTR="supsimage  x1beg=$x1beg f1=0 f2=0 key=f2 label1=$LABEL1 label2=$LABEL2 perc=$perc "


$PLOTR < $FILE1  title=$TITLE1  > p 
$PLOTR < $FILE2  title=$TITLE2  > pp
$PLOTR < $FILE3  title=$TITLE3  > ppp
$PLOTR < $FILE4  title=$TITLE4  > pppp

supsmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > ~/ps/$FILE

gv ~/ps/$FILE &

