#! /bin/sh
# PLOTS 




FILE=fig4radoncomp.ps
FILE0=sumiss2
FILE1=$FILE0'cdps'
FILE2=$FILE0'demulhr'
FILE3=$FILE0'demul'
FILE4=$FILE0'demul'

suwind key=cdp min=1100 max=1200 j=50 < $FILE0 | sugain tpow=2.0 | susort cdp offset > $FILE1

OPTIONNORM='y'
OPTIONNUM='2'

TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"

LABELT="time (sec)" 
LABELO="offset(feet)"
LABELR="q(s/m^2)"
LABELTAU="tau (sec"

PLOTX="supswigp f1=0 f2=0 key=offset label1=$LABELT label2=$LABELO clip=1.1"
PLOTR="supswigp f1=0 f2=0 key=f2 label1=$LABELTAU label2=$LABELR clip=1.1"

echo $PLOTX


case $OPTIONNORM in
y*)
suop op=norm < $FILE1 > aux1
suop op=norm < $FILE2 > aux2
suop op=norm < $FILE3 > aux3
suop op=norm < $FILE4 > aux4

$PLOTX < aux1 title=$TITLE1  > p  
$PLOTX < aux2  title=$TITLE2  > pp
$PLOTX < aux3  title=$TITLE3  > ppp  
$PLOTX < aux4  title=$TITLE4  > pppp
;;

n*)
$PLOTX < $FILE1  title=$TITLE1  > p  
$PLOTX < $FILE2  title=$TITLE2  > pp
$PLOTX < $FILE3  title=$TITLE3  > ppp  
$PLOTX < $FILE4  title=$TITLE4  > pppp
;;
esac


case $OPTIONNUM in
2*)
psmerge in=p in=pp scale=0.6,0.6 translate=-1,5 translate=4,5 > ~/ps/$FILE
;;
3*)
psmerge in=p in=pp in=ppp  scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0  > ~/ps/$FILE
;;
4*)
psmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > ~/ps/$FILE
;;
esac

gv ~/ps/$FILE &








