#! /bin/sh
# PLOTS 
# Plot for semblance analysis.
# The ps files must be produced first with Velan5  (OPTIONPS='y')
# Daniel Trad- UBC Nov 1999
  
FILE=fig16mig.ps

FILE0=miss2.su
FILEN=miss2.su
OPTIONGAIN='n'
OPTIONNUM='4'
PLOTPS="supswigp key=offset label1=$LABELT label2=$LABELO perc=100"

case $OPTIONGAIN in
y*)
echo 'Correcting by spherical spreading'
sugain tpow=2.0 < $FILE0 > pp; cp pp $FILE0
;;
esac

suwind key=cdp min=1028 max=1028  < $FILE0 | $PLOTPS title="CMP 1028"  > p 
suwind key=cdp min=1102 max=1102 < $FILE0 | $PLOTPS title="CMP 1102" > pp 
suwind key=cdp min=1176 max=1176 < $FILE0 | $PLOTPS title="CMP 1176" > ppp 
suwind key=cdp min=1250 max=1250 < $FILE0 | $PLOTPS title="CMP 1250" > pppp 


case $OPTIONNUM in
2*)
psmerge in=p in=pp  scale=0.6,0.6 translate=-1,5 translate=4,5 > ~/ps/$FILE
;;
3*)
psmerge in=p in=pp in=ppp  scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0  > ~/ps/$FILE
;;
4*)
psmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > ~/ps/$FILE
;;
esac

gv ~/ps/$FILE &








