#!/bin/sh
window="x2beg=-500 x2end=500  x1beg=0. x1end=2  "

suxwigb key=offset  < $1 title=$1 $window&

if [ 0 = 1 ]; then
window="x2beg=500 x2end=3000  x1beg=6.4 x1end=7 clip=2.0 "
supswigb key=offset < $1 title=$2 $window label1='Time(s)' label2='Offset(m)' f1=5.5 interp=1 > $1".ps"
gv $1".ps"

fi
