#! /bin/sh


set -x 


#FILE=cdp1000.su

clip=1.35

supswigp < "$1" key=offset x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end clip=$clip \
title="$1"  > ~/ps/"$1".ps

supswigp < "$2" key=offset x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end clip=$clip \
title="$2" > ~/ps/"$2".ps

supswigp < "$3" key=offset x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end clip=$clip \
title="$3"  > ~/ps/"$3".ps

supswigp < "$4" key=offset x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end clip=$clip \
title="$4" > ~/ps/"$4".ps



convert ~/ps/"$1".ps  ~/ps/jpg/"$1".jpg
convert ~/ps/"$2".ps  ~/ps/jpg/"$2".jpg
convert ~/ps/"$3".ps  ~/ps/jpg/"$3".jpg
convert ~/ps/"$4".ps  ~/ps/jpg/"$4".jpg





