#! /bin/sh
# PLOTS 
# Plot for data, primaries and multiples.
# Daniel Trad- UBC Nov 1999
  
FILE=fig2hyprad_after.ps
clipx=100
clipx2=95

# PLot model

FILEN=cdp1000g
x1beg=0
x1end=7
x2beg=-16000
x2end=0


FILE1=$FILEN'.sugap'
FILE2=$FILEN'.surad'
FILE3=$FILEN'.sumix_down_LI1'
FILE4=$FILEN'.sumix_toep2'

OPTIONPLOT='ps'
OPTIONNUM='4'

TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"

LABEL1="time(sec)" 
LABEL2="offset(feet)"
LABELR="q(s^2/feet^2)"


case $OPTIONPLOT in
ps*)
PLOTR="supswigp f1=0 f2=0 key=f2 label1=$LABEL1 label2=$LABELR perc=99.5"
PLOTX="supswigp x2beg=$x2beg x2end=$x2end key=offset label1=$LABEL1 label2=$LABEL2 clip=$clipx"
PLOTX2="supswigp x2beg=$x2beg x2end=$x2end key=offset label1=$LABEL1 label2=$LABEL2 clip=$clipx2"
PLOTD="supswigp key=offset label1=$LABEL1 label2=$LABEL2 clip=$clip"
PLOTI="supswigp key=offset label1=$LABEL1 label2=$LABELR clip=$clip"
;;
esac


case $OPTIONPLOT in
ps*)
$PLOTX < $FILE1  title=$TITLE1  > p  
$PLOTR < $FILE2  title=$TITLE2  > pp
$PLOTX2 < $FILE3  title=$TITLE3  > ppp 
$PLOTX2 < $FILE4  title=$TITLE4  > pppp
;;
esac

case $OPTIONNUM in
2*)
psmerge in=p in=pp scale=0.6,0.6 translate=-1,5 translate=4,5 > ~/ps/$FILE
;;
3*)
psmerge in=p in=pp in=ppp  scale=0.42,0.42 translate=0,3 translate=3,3 translate=6,3  > ~/ps/$FILE
;;
4*)
psmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > ~/ps/$FILE
;;
esac

gv ~/ps/$FILE &





