#! /bin/sh
# PLOTS 
# Plot for data, primaries and multiples.
# Daniel Trad- UBC Nov 1999

FILE=fig_csp_misscn1.ps
clipx=20
clipx2=5
clipx3=2.5
perc=99

# PLot model

FILEN=cdp1000
x1beg=1.5
x1end=7
x2beg=-20000
x2end=0


FILE1=$FILEN'r.su'
FILE2=$FILEN'.csp.su'
FILE3=$FILEN'.rmcsp.su'
FILE4=$FILEN'r.su.1000.ps'
FILE5=$FILEN'.csp.su.1000.ps'
FILE6=$FILEN'.rmcsp.su.1000.ps'


TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"
TITLE5="(e)"
TITLE6="(f)"


LABEL1="time(sec)" 
LABEL2="offset(feet)"
LABELR="q(s^2/feet^2)"


PLOTD="supswigp x2beg=$x2beg x2end=$x2end key=offset label1=$LABEL1 label2=$LABEL2 clip=$clipx x1beg=$x1beg x1end=$x1end"
PLOTX="supswigp x2beg=$x2beg x2end=$x2end key=offset label1=$LABEL1 label2=$LABEL2 perc=$perc x1beg=$x1beg x1end=$x1end"
PLOTX2="supswigp x2beg=$x2beg x2end=$x2end key=offset label1=$LABEL1 label2=$LABEL2 perc=$perc x1beg=$x1beg x1end=$x1end"



$PLOTD < $FILE1  title=$TITLE1  > p  
$PLOTX < $FILE2  title=$TITLE2  > pp
$PLOTX2 < $FILE3  title=$TITLE3  > ppp 
cp $FILE4 pppp
cp $FILE5 ppppp
cp $FILE6 pppppp



psmerge in=p in=pp in=ppp in=pppp in=ppppp in=pppppp scale=0.5,0.5 translate=0,5 translate=4,5  translate=8,5 translate=0,0 translate=4,0 translate=8,0 > $HOME'/ps/'$FILE

#psmerge in=p in=pp in=ppp  scale=0.5,0.5 translate=0,5 translate=4,5  translate=8,5  > $HOME'/ps/'$FILE

gv ~/ps/$FILE &

















