#! /bin/sh
# PLOTS 
# Plot for radon outputs
# Daniel Trad- UBC Nov 1999
set -x  
FILE=fig3avo.ps

FILEN=data2

FILE1=$FILEN".surad"
FILE2=$FILEN".zeros.surad"
FILE3=$FILEN".zeros.suradpos"
FILE4=$FILEN".zeros.suradneg"

OPTIONNUM='4'
TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"

LABELT="time (sec)" 
LABELO="offset(m)"
LABELR="s2/m2"
LABELTAU="tau(sec)"
LABELFREQ="Freq(Hz)"
LABELFREQ2="q"

PLOTX="supswigp f1=0 f2=0 key=offset label1=$LABELT label2=$LABELO "
PLOTR="supswigp f1=0 f2=0 key=offset label1=$LABELTAU label2=$LABELR perc=100 "

$PLOTR < $FILE1 > p title=$TITLE1 
$PLOTR < $FILE2 > pp title=$TITLE2 
#$PLOTR < $FILE2 > pp title=$TITLE2
$PLOTR < $FILE3 > ppp title=$TITLE3 
$PLOTR < $FILE4 > pppp title=$TITLE4 

case $OPTIONNUM in
2*)
psmerge in=$FILE1 in=$FILE2  scale=0.6,0.6 translate=-1,5 translate=4,5 > ~/ps/$FILE
;;
3*)
psmerge in=$FILE1 in=$FILE2 in=$FILE3  scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0  > ~/ps/$FILE
;;
4*)
psmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > ~/ps/$FILE
;;
esac

gv ~/ps/$FILE &










