#! /bin/sh
# PLOTS 
# Plot for data, primaries and multiples.
# Daniel Trad- UBC Nov 1999
set -x   
#MACHINE="sun "
MACHINE="home"

FILE=data2mll
FILEPS=$FILE'.ps'
FILEJPG=$FILE'.jpg'

# PLot model
if [ MACHINE = "sun " ]; then
    FILEN=$FILE    
else
    FILEN=$FILE
fi



FILE1=$FILEN'.su'
FILE2=$FILEN'.cdp.prt.su'
FILE3=$FILEN'.cdp.lrt.su'
FILE4=$FILEN'.cdp.hyb.su'

OPTIONPLOT='i'

OPTIONNUM='3'

TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"
TITLE5="(e)"
TITLE6="(f)"

LABEL1="time(sec)" 
LABEL2="offset(m)"
LABELR="q(s/m^2)"
LABELD="dV(m^2/s^2)"
LABELT="trace#"

case $OPTIONPLOT in
y*)
PLOTR="supswigp f1=0 f2=0 key=f2 label1=$LABEL1 label2=$LABELR"
PLOTI="supswigp f1=0 f2=0 key=offset label1=$LABEL1 label2=$LABELR"
PLOTX="supswigp f1=0 f2=0 key=offset label1=$LABEL1 label2=$LABEL2 perc=99"
GAIN="sugain agc=1 "
;;
w*|x*|a*|r*)
PLOTF="supswigp x2beg=-15993 x2end=0 key=offset label1=$LABEL1 label2=$LABELR perc=99"
PLOTR="supswigp key=f2 label1=$LABEL1 label2=$LABELR "
PLOTX="supswigp key=offset label1=$LABEL1 label2=$LABEL2 "
PLOTI="supswigp key=offset label1=$LABEL1 label2=$LABELR perc=99"
PLOTT="supswigp label1=$LABEL1 label2=$LABELT "
PLOTD="supswigp key=offset label1=$LABEL1 label2=$LABELD perc=99.9"
SUXIM="supsimage label1=$LABEL1 label2=$LABELT "
GAIN="sugain agc=1 "
;;
esac


case $OPTIONPLOT in
n*)
#$PLOTM < $FILE1  title=$TITLE1  > p  
$GAIN < $FILE1 | $PLOTX  title=$TITLE1  > p
$GAIN < $FILE2 | $PLOTR perc=99.5  title=$TITLE2  > pp
#$PLOTR < $FILE2  title=$TITLE2  > pp
$GAIN < $FILE3 | $PLOTX  title=$TITLE3  > ppp 
$GAIN < $FILE4 | $PLOTR perc=99.5 title=$TITLE4  > pppp
#$PLOTR < $FILE4  title=$TITLE4  > pppp

;;

x*) 
clip=2.4
#clip=0.0668748

$PLOTX < $FILE1  title=$TITLE1  clip=$clip > p  
$PLOTX < $FILE2  title=$TITLE2  clip=$clip > pp
$PLOTX < $FILE3  title=$TITLE3  clip=$clip > ppp
$PLOTX < $FILE4  title=$TITLE4  clip=$clip > pppp 

#$SUXIM < $FILE1  title=$TITLE1  clip=$clip > p  
#$SUXIM < $FILE2  title=$TITLE2  clip=$clip > pp
#$SUXIM < $FILE3  title=$TITLE3  clip=$clip > ppp
#$SUXIM < $FILE4  title=$TITLE4  clip=$clip > pppp 

;;
w*) # read from workstation and plot in pc
suswapbytes < $FILE1 | $PLOTX  title=$TITLE1  > p  
suswapbytes < $FILE2 | $PLOTX  title=$TITLE2  > pp
cp $FILE3 ppp
cp $FILE4 pppp

#suswapbytes < $FILE3 | $PLOTR  title=$TITLE3  > ppp 
#suswapbytes < $FILE4 | $PLOTR  title=$TITLE4  > pppp
;;

a*) 
clip=2.4
#clip=0.0668748

$GAIN < $FILE1  | $PLOTX title=$TITLE1  clip=$clip > p  
$GAIN < $FILE2  | $PLOTX title=$TITLE2  clip=$clip > pp
$GAIN < $FILE3  | $PLOTX  title=$TITLE3  clip=$clip > ppp
$SUXIM < $FILE4  title=$TITLE4  perc=95 > pppp 

;;


r*) 
clip=2.4
$PLOTX < $FILE1  title=$TITLE1  clip=$clip > p  
suop2 $FILE1 $FILE2 | $PLOTX title=$TITLE2  clip=$clip > pp
suop2 $FILE1 $FILE3 | $PLOTX title=$TITLE3  clip=$clip > ppp
suop2 $FILE1 $FILE4 | $PLOTX title=$TITLE4  clip=$clip > pppp 

;;


i*) 
clip=4.0
perc=99.95

#clip=0.0668748

FILE1=$FILEN'.su'
FILE2=$FILEN'.hybrid.iter1.su'
FILE3=$FILEN'.hybrid.iter5.su'
FILE5=$FILEN'.cdp.iter1.su'
FILE6=$FILEN'.cdp.iter5.su'


SUXIM="supsimage label1=$LABEL1 label2=$LABELT "
$SUXIM < $FILE1   title=$TITLE1 clip=$clip > p  
$SUXIM < $FILE2   title=$TITLE2  perc=$perc > pp
$SUXIM < $FILE3   title=$TITLE3  perc=$perc > ppp
suop2 $FILE5 $FILE6 | $SUXIM title=$TITLE4  clip=$clip > pppp 
$SUXIM < $FILE5   title=$TITLE5  clip=$clip > ppppp 
$SUXIM < $FILE6   title=$TITLE6  clip=$clip > pppppp

;;

esac

case $OPTIONNUM in
2*)
psmerge in=p in=pp scale=0.6,0.6 translate=-1,5 translate=4,5 > ~/ps/$FILEPS
;;
3*)
psmerge in=p in=pp in=ppp  scale=0.42,0.42 translate=0,3 translate=3,3 translate=6,3  > ~/ps/$FILEPS
;;
4*)
psmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > $HOME'/ps/'$FILEPS
;;
6*)
psmerge in=p in=pp in=ppp in=pppp in=ppppp in=pppppp scale=0.35,0.35 translate=0,4 translate=2.6,4 translate=5.2,4 translate=0,0 translate=2.6,0 translate=5.2,0  > $HOME'/ps/'$FILEPS
;;



esac

ghostview $HOME'/ps/'$FILEPS &
#convert $HOME'/ps/'$FILEPS  $HOME'/jpg/'$FILEJPG









