#!/bin/sh
#figures for interp5D documentation package

set -x

TITLE1="title=(a)" 
TITLE2="title=(b)" 
TITLE3="title=(c)" 
TITLE4="title=(d)" 
TITLE5="title=(e)" 
TITLE6="title=(f)"
TITLE7="title=(g)"
TITLE8="title=(h)"
TITLE9="title=(i)"


if [ 1 = 1 ]; then

#input
FILE1=/home/dtrad/modules/dft/in
FILE1b=/home/dtrad/modules/dft/suin

#output
FILE2=/home/dtrad/modules/dft/inback
FILE2b=/home/dtrad/modules/dft/suinback
#diff
FILE3=/home/dtrad/modules/dft/diff

#add header for differences
ns=530
dt=4000
d2=15
f2=0

suaddhead < $FILE1 ns=$ns | \
sushw key=dt,d2,f2 a=$dt,$d2,$f2 > $FILE1b
suaddhead < $FILE2 ns=$ns | \
sushw key=dt,d2,f2 a=$dt,$d2,$f2 > $FILE2b

#output
FILE="/home/dtrad/psfig/${1}.ps"

DIFF="sudiff"
PLOTI="supsimage clip=1 label1=Time(s) label2=Offset(m) x1end=1.1 x2end=1000 legend=1 "

PLOTX="supswigb clip=1 label1=Time(s) label2=Offset(m) x1end=1.1 x2end=1000 legend=1 "

$DIFF  $FILE2b $FILE1b > $FILE3

#$PLOTI < $FILE1b > p1 $TITLE1
#$PLOTI < $FILE2b > p2 $TITLE2
#$PLOTI < $FILE3 > p3 $TITLE3

$PLOTX < $FILE1b > p1 $TITLE1
$PLOTX < $FILE2b > p2 $TITLE2
$PLOTX < $FILE3 > p3 $TITLE3



/home/dtrad/cwp/bin/psmerge in=p1 in=p2 in=p3 scale=0.34,0.37 scale=0.34,0.37 scale=0.68,0.37 translate=1,7 translate=4,7 translate=1,3.5 > $FILE
#okular $FILE
fi 

