#! /bin/sh

supswigp < sucdps2 f1=0 f2=0 key=offset title="(a)" label1="time (sec)" label2="offset(m)" > p

supswigp < sucdps2rad f1=0 f2=0 key=f2 title="(b)" label1="tau (sec)" label2="q(s/m^2)" perc=99 > pp

#supswigp < sucdps2 f1=0 f2=0 key=f2 title="(c)" label1="tau (sec)" label2="q(s/m^2)" perc=100 > ppp

supswigp < sucdps2rec f1=0 f2=0 key=offset title="(c)" label1="time (sec)" label2="offset(m)" perc=100 > ppp

supswigp < sucdps2recb f1=0 f2=0 key=offset title="(c)" label1="time (sec)" label2="offset(m)" perc=100 > pppp
#supswigp < sucdps2radCG f1=0 f2=0 key=f2 title="(d)" label1="tau (sec)" label2="q(s/m^2)" perc=100 > pppp

#sufft < sucdps2radT | suamp | supswigp f1=0 f2=0 key=f2 title="(b)" label1="freq (Hz) " label2="q(s/m^2)" > pp

FILE=fig1td.ps

psmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > ~/ps/$FILE
#psmerge in=p in=pp scale=0.6,0.6 translate=-1,5 translate=4,5 > /home/dtrad/ps/fig10cand.ps

gv ~/ps/$FILE &








