#! /bin/sh
# PLOTS 
# Plot for separation of events in aliased data.
# Daniel Trad- UBC March 2001
set -x 

METHOD1='SOLtoep';
METHOD2='TFD';


FILEN=surio1  
FILE='/home/dtrad/ps/'${FILEN}'_alias.ps'

CLIP=0.3

# PLot model

LEGEND1='non-sparse'
LEGEND2='sparse'

FILE1=$FILEN
FILE2=$FILEN'rad'${METHOD1}
FILE3=$FILEN'recb'${METHOD1}
FILE4=$FILEN'rad'${METHOD2}
FILE5=$FILEN'recb'${METHOD2}

PSPLOT1=p1
PSPLOT2=p2
PSPLOT3=p3
PSPLOT4=p4
PSPLOT5=p5
PSPLOT6=p6
PSPLOT7=p7
PSPLOT8=p8
PSPLOT9=p9

OPTIONNUM='9'

TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"
TITLE5="(e)"
TITLE6="(f)"
TITLE7="(g)"
TITLE8="(h)"
TITLE9="(i)"


TITLE1="(a) data"
TITLE2="(b) f-k spectrum "
TITLE3="(c) RT - ${LEGEND1}"
TITLE4="(d) RT spectrum - ${LEGEND1}"
TITLE5="(e) Separated event "
TITLE6="(f) RT - ${LEGEND2}"
TITLE7="(g) RT spectrum - ${LEGEND2}"
TITLE8="(h) Separated event "


LABEL1="time(sec)" 
LABEL2="offset(m)"
LABELR2="q(s/m^2)"
LABELR1="tau(sec)"
LABELRF1="f(Hz)"
LABELK="Kx"
LABELF="freq(Hz)"

PLOTR="supswigp f1=0 f2=0 key=f2 label1=$LABELR1 label2=$LABELR2 perc=99.95"
PLOTRF="supswigp key=f2 label1=$LABELRF1 label2=$LABELR2 perc=100"
#PLOTX="supswigp key=offset label1=$LABEL1 label2=$LABEL2 clip=${CLIP}"
PLOTX="supswigp key=offset label1=$LABEL1 label2=$LABEL2 perc=99.9"
PLOTD="supswigp key=offset label1=$LABEL1 label2=$LABEL2 clip=2.5 x2beg=-1250 x2end=1250"
PLOTI="supswigp key=offset label1=$LABEL1 label2=$LABELR"
PLOTIMAGE="supsimage label1=$LABELF label2=$LABELK perc=99"

$PLOTX < $FILE1  title=$TITLE1  > $PSPLOT1  
suspecfk < $FILE1 | $PLOTIMAGE title=$TITLE2 >  $PSPLOT2
$PLOTR < $FILE2  title=$TITLE3  > $PSPLOT3
sufft < $FILE2 | suamp | $PLOTRF title=$TITLE4 > $PSPLOT4
$PLOTX < $FILE3  title=$TITLE5  > $PSPLOT5   
$PLOTR < $FILE4  title=$TITLE6  > $PSPLOT6
sufft < $FILE4 | suamp | $PLOTRF title=$TITLE7 > $PSPLOT7
$PLOTX < $FILE5  title=$TITLE8  > $PSPLOT8   


psmerge in=$PSPLOT1 in=$PSPLOT2 in=$PSPLOT3 in=$PSPLOT4 in=$PSPLOT5 in=$PSPLOT6 in=$PSPLOT7 in=$PSPLOT8 scale=0.36,0.36  translate=1.5,7 translate=4.3,7  translate=0,3.5 translate=2.8,3.5 translate=5.6,3.5 translate=0,0 translate=2.8,0 translate=5.6,0 > "${FILE}"


gv $FILE &

















