#! /bin/sh
# PLOTS 
# Plot for interpolation of mixed shots using suinterpfk4
# Daniel Trad- UBC Nov 1999
set -x 

FIGURE="$1"

FILEN=kencmpwin


FILE1=$FILEN'.su'
FILE2=$FILEN'.surad0FK'
FILE3=$FILEN'.suradFK'
FILE4=$FILEN'.surecFK'
FILE5=$FILEN'.suresFK'


TITLE1="(a)" #data
TITLE2="(b)" #migrated data
TITLE3="(c)" #mute
TITLE4="(d)" #diffractions 
TITLE5="(d)" #data after subtraction 


LABEL1="Time(s)" 
LABEL2="Offset(m)"

LABEL1="Time" 
LABEL2="Offset"
hideaxes="d1num=10 d2num=1000 f1num=100 f2num=100000"

parimage="f2=213 d2=50 clip=$2"
parwigle="clip=2"
PLOTX="supswigp key=offset label1=$LABEL1 label2=$LABEL2 ${parwigle} ${hideaxes} "
PLOTX2="supsimage label1=$LABEL1 label2=$LABEL2 ${parimage} ${hideaxes} "


if [ $FIGURE -eq 1 ];then 

image=1 # image
#image=0 # wigle plot 
if [ $image -eq 1 ]; then
FILE='suinterpfk_keni_secret.ps'  
suwind key=offset min=0 < $FILE1 | sushw key=delrt a=5500 | $PLOTX2 title=$TITLE1  > p  
suwind key=offset min=0 < $FILE2 | sushw key=delrt a=5500 | $PLOTX2 title=$TITLE2  > pp
suwind key=offset min=0 < $FILE3 | sushw key=delrt a=5500 | $PLOTX2 title=$TITLE3  > ppp
suwind key=offset min=0 < $FILE4 | sushw key=delrt a=5500 | $PLOTX2 title=$TITLE4  > pppp 
else
FILE='suinterpfk_kenw.ps' 

suwind key=offset min=0 < $FILE1 | sushw key=delrt a=5500 | $PLOTX title=$TITLE1  > p  
suwind key=offset min=0 < $FILE2 | sushw key=delrt a=5500 | $PLOTX title=$TITLE2  > pp
suwind key=offset min=0 < $FILE3 | sushw key=delrt a=5500 | $PLOTX title=$TITLE3  > ppp
suwind key=offset min=0 < $FILE4 | sushw key=delrt a=5500 | $PLOTX title=$TITLE4  > pppp 
fi


supsmerge in=p in=pp in=ppp in=pppp  scale=0.5,0.5 scale=0.5,0.5 scale=0.5,0.5 scale=0.5,0.5  scale=0.45,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 translate=8,2 > ~/ps/$FILE

gv ~/ps/$FILE &

elif [ $FIGURE -eq 2 ];then 

FILE='suinterpfk_ken2_secret.ps' 
suwind key=offset min=0 < $FILE1 | sushw key=delrt a=5500 | $PLOTX2 title=$TITLE1  > p  
suwind key=offset min=0 < $FILE5 | sushw key=delrt a=5500 | $PLOTX2 title=$TITLE2  > pp

supsmerge in=p in=pp scale=0.5,0.5 scale=0.5,0.5 scale=0.5,0.5 scale=0.5,0.5  scale=0.45,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 translate=8,2 > ~/ps/$FILE
gv ~/ps/$FILE &


fi


exit 0



















