#! /bin/sh
# Xsuradonfk_ken --- Attenuation of difractions with  
# non apex centered Radon Transform.
# Data contain multiples of diffractions. 
#
# data preprocessing:
# Althouth the data is a real data set, for this example we need to take a
# window, and make the data to look symmetric 
# from  kencmpsnonmo.su take cdp 5300 and window from 5.5s to end.
# Data name kencmpwin0.su
# then make the data symmetric by 
# suchw key1=offset key2=offset b=-1 < kencmpwin0.su > pp
# cat pp kencmpwin0.su > kencmpwin.su
# sushw key=delrt a=0 < kencmpwin.su > pp
# susort +offset < pp >  kencmpwin.su
# Xsetntr kencmpwin.su
######################################################################
# Author: Daniel Trad- November 2001
set -x
#filen=lineken0b
#filein=$filen".su"
# Uncomment these two lines if all cdps are going to be output
# to a single file

#fileout=$filen"a.su"
#rm $fileout


filen=cdps5800_6300
fileorig="${filen}orig.su"
fileclean="${filen}clean.su"
filediff="${filen}diff.su"

#rm $fileorig
#rm $fileclean
#rm $filediff



cdpmin=5800
cdpmax=5899


dcdp=1


cdp=$cdpmin
while [ $cdp -le $cdpmax ]
do
cdporig="cdp${cdp}orig.su"
cdpdiff="cdp${cdp}diff.su"
cdpclean="cdp${cdp}clean.su"

cat $cdpclean >> $fileclean
cat $cdporig >> $fileorig
cat $cdpdiff >> $filediff

cdp=` expr $cdp + $dcdp`


done

exit 0








