#! /bin/sh
# Xradon --- Test program for Linear Parabolic and Hyperbolic Radon Transform.
######################################################################
# Example: cdp1000 from misscn1.su 
# 
#######################################################################
# Author: Daniel Trad- June 2000

# Some shortcuts for plots

PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650"

set -x

FILE=cdps2
FILEN=$FILE'.td.su'
FILE=$FILE'.su'
FILETEMP=pp
FILETEMP2=ppp
FILENMO=$FILE'nmo'
FILEGAP=$FILE'gap'
FILEOFF=$FILE'off'
FILERAD=$FILEN'rad'
FILEREC=$FILEN'rec'
FILERES=$FILEN'res'
FILERADOFF=$FILEN'radoff'
FILERAD2=$FILEN'radb'
FILEREC2=$FILEN'recb'
FILEOFF2=$FILEOFF  # Final offset in which data will be resampled 

# Options
OPTIONGAP='n'
OPTIONSETNTR='y'
OPTIONGETH='y'
OPTIONFILT='n'
OPTIONAGC='n'
OPTIONRAD='n'
OPTIONRADF='n'
OPTIONINT='y'
OPTIONMUTE='n'
OPTIONREC='n'
OPTIONRES='n'

# PASS BAND FILTER
F=1,10,70,80
AMPS=0,1,1,0
# RADON (see suhrrtf for more details)
METHOD=8
EPS1=1e-3  # Variance of the noise
EPS2=1e-3 
QMIN=0  # Min q
QMAX=6e-7
QMAX=400;
QMIN=-400;
NQ=30      # NP traces
FMAX=70     # max freq to compute
RTMETHOD=3 # 1=LRT 2=PRT 3=HRT
COSTFLAG=0 # =1 PLOT COST FUNCTIONS (SLOWER)
EPS=0.01      # =0 FOR METHOD 2 
NORM=1     # L1 NORM
STEP=0.9  # Step less 1
THRES=0.5 
TESTADJ=1
VERBOSE=1
SMOOTH=0
ITER_END=3
ITERCG=15
offsetfile=$FILEOFF'2'

if [ $OPTIONINT = "y" ] ;
then 
fmax=70
eps1=1e-3
eps2=1e-3
eps=0.01
norm=0
nq=150
dperv=0.01;
dq=1e-10;
pervmin=60;
perc=100
step=0.95
qmin=-400
qmax=400
itercg=30
iter_end=2
smooth=0
testadj=0
method=$1
resample=2;
offsetfile=$FILEOFF'2'
mute=0;
keepdata=1;
parmute=6.2e-8;
flagvel=2;
centralq=40
if [ $flagvel -eq 2 ]; then
    pervmin=5e-10
fi

fi # end of OPTIONINT

cdp=547
tnmo=0.0383,0.4596,0.6685,0.8669,0.8704,1.086,1.226,1.421,1.741,1.971,2.159
vnmo=2508,2725,2765,2974,2974,3166,3335,3511,3455,3399,3543
#tnmo=0,2
#vnmo=4000,4000

tvel=$tnmo
vel=$vnmo
TVEL=$tvel
VEL=$vel

cp $FILE $FILETEMP
# Save offset  for inverse radon transform

case $OPTIONGETH in
y*)
sugethw key=offset output=geom < $FILE > $FILEOFF
;;
esac

case $OPTIONGAP in
y*)
suwind key=offset abs=1 min=1000 max=14000 < $FILETEMP > $FILETEMP2
#suwind key=offset j=4 < $FILETEMP > $FILETEMP2
cp $FILETEMP2 $FILETEMP
suwind key=tracl reject=40,41,42,43,44,45,46,47,48  < $FILETEMP > $FILETEMP2
#suwind key=offset j=4 < $FILETEMP > $FILETEMP2
cp $FILETEMP2 $FILETEMP
suwind key=tracl reject=60,61,62  < $FILETEMP > $FILETEMP2

cp $FILETEMP2 $FILETEMP
cp $FILETEMP  $FILEGAP
$PLOTX perc=$perc < $FILETEMP &
;;
esac



case $OPTIONSETNTR in
y*)
ntr=`surange < $FILETEMP | sed 1q | sed 's/traces://'`
sushw key=ntr a=$ntr < $FILETEMP > $FILETEMP2
cp  $FILETEMP2 $FILETEMP
;;
esac

case $OPTIONFILT in
y*)
sufilter f=$F amps=$AMPS < $FILETEMP > $FILETEMP2;
cp  $FILETEMP2 $FILETEMP
;;
esac




case $OPTIONRAD in
y*)
#Forward  Radon transform
suradtd method=$METHOD  eps1=$EPS1 eps2=$EPS2 iter_end=$ITER_END qmin=$QMIN qmax=$QMAX nq=$NQ freq=$FMAX rtmethod=$RTMETHOD costflag=$COSTFLAG itercg=$ITERCG eps=$EPS norm=$NORM step=$STEP thres=$THRES smooth=$SMOOTH testadj=$TESTADJ verbose=$VERBOSE vel=$VEL tvel=$TVEL pervmin=$pervmin dperv=$dperv crude=0 < $FILETEMP  > $FILERAD
$PLOTR perc=$perc < $FILERAD &

#Inverse Radon Transform
suradtdi method=$METHOD rtmethod=$RTMETHOD fmax=$FMAX offsetfile=$FILEOFF2 \
smooth=0 vel=$VEL tvel=$TVEL verbose=0 < $FILERAD > $FILEREC2
$PLOTX perc=$perc < $FILEREC2 &
;;
esac

case $OPTIONINT in
y*)
#Forward  Radon transform and Inverse RT
suradon1 method=$method  eps1=$eps1 eps2=$eps2 iter_end=$iter_end qmin=$qmin qmax=$qmax nq=$nq freq=$fmax rtmethod=$rtmethod costflag=$costflag itercg=$itercg eps=$eps norm=$norm step=$step thres=$thres smooth=$smooth testadj=$testadj verbose=$verbose vel=$vel tvel=$tvel pervmin=$pervmin dperv=$dperv modelfile=$FILERAD dh2=50 precond=0 t0=0 offsetfile=$offsetfile  resample=$resample  dhmin=17 mute=$mute parmute=$parmute keepdata=$keepdata flagvel=$flagvel centralq=$centralq < $FILETEMP > $FILEREC2
$PLOTR perc=$perc < $FILERAD title="Modified Radon transform" &
$PLOTX perc=$perc < $FILE title="Original data"&
$PLOTX perc=$perc < $FILEREC2 title="Interpolated data" &
;;
esac



# Here we perform PRT to compare 
case $OPTIONRADF in
y*)
sunmo tnmo=$TVEL vnmo=$VEL smute=3 < $FILETEMP > $FILETEMP2 ; cp $FILETEMP2  $FILETEMP

#Forward  Radon transform in Frequency
suhrrtf method=2  eps1=.001 eps2=.001 iter_end=5 qmin=-2e-8 qmax=3e-7 nq=100 freq=70 rtmethod=2 costflag=0 itercg=20 eps=0 norm=1 step=$STEP factor=0.8  < $FILETEMP  > $FILERAD
$PLOTR perc=$perc < $FILERAD title="Toeplitz Parabolic Radon transform" &

if [ $OPTIONMUTE = "y" ]; then
    Xmuterad $FILERAD
    FILERAD=$FILERAD'mute'    
fi


#Inverse Radon Transformr
suhrrti rtmethod=2 offsetfile=$offsetfile  fmax=70 < $FILERAD  > $FILEREC
sunmo tnmo=$TVEL vnmo=$VEL  invert=1 smute=3 < $FILEREC > $FILEREC2
$PLOTX perc=$perc < $FILEREC2 title="Interpolated with Toeplitz Parabolic Radon transform" &

# Keep original traces and set ntr
sumixgathers $FILE $FILEREC2 > $FILETEMP;
ntr=`surange < $FILETEMP | sed 1q | sed 's/traces://'`
sushw key=ntr a=$ntr < $FILETEMP > $FILEREC2

;;

esac

case $OPTIONRES in
y*)
suop2 $FILE $FILEREC2 op=diff > $FILERES
$PLOTX perc=100 < $FILERES title="Residuals" &
;;
esac


exit 0  










































