#! /bin/sh
# Xradon_cdp1000_demul --- Multiple attenuation with  Radon Transform.
######################################################################
# Author: Daniel Trad- November 2001

# Some shortcuts for plots
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650"

set -x

METHOD='SOL'
#METHOD='TFD'
#METHOD='HRF'
METHOD='TD'

RADONFORW='y'

sufix=${METHOD}
echo $METHOD

if [ ${METHOD} = 'SOL' ]; then
    sufix="${1}"
fi

FILE=cdp1000g.su; clip=95  #clip corresponding to perc=97

FILEN=$FILE
FILEGAP=$FILE'gap'
FILETEMP=pp
FILETEMP2=ppp

offsetfile=$FILE'off'
FILERAD=${FILEN}'rad'${sufix}
FILERAD2=${FILEN}'rad'${sufix}
FILEREC=$FILEN'rec'${sufix}
FILEREC2=$FILEN'recb'${sufix}
FILEMIX=$FILEN'mix'${sufix}
FILERES=$FILEN'res'${sufix}
FILERESAMP=$FILE'resamp'${sufix}
RESAMPLE='n'
PAR="stkvel.misscn3b.su"
par=$PAR

# Options
SETNTR='y'
GETH='y'
FILT='n'
TAPER='n'
OPTIONGAP='y'

# PASS BAND FILTER
F=1,10,70,80
AMPS=0,1,1,0
# RADON
#***Freq############################ 

VERBOSE=1
fold=1
buffer=10; 
iter_end=4
sinc=0;
parmute=3e-9
parmute=22e-9
nq=90
under=0.999
over=1.001
qmin=-2e-9
factor=1.1
fmax=100

if [ $METHOD = 'SOL' ]; then
    eps1=1e-2
    eps2=1e-2
    factor=1.6
    norm=0
    eps=1e-7
    rtmethod=2
    itercg=25
    verbose=0
    depth=1000
    PROGRAM=suradonsolver
    solver="$1"
elif [ $METHOD = 'TFD' ]; then
    eps1=1e-2
    eps2=1e-2
    factor=1.5
    norm=0
    eps=1e-7
    rtmethod=2
    itercg=25
    verbose=0
    depth=1000
    PROGRAM=suradonwtcgls_tfd
    solver="$1"
elif [ $METHOD = 'TD' ]; then
    eps1=1e-3
    eps2=1e-3
    PROGRAM=suradontd1
    eps=0.01
    dperv=0.03;
    dperv=0.03;
    pervmin=0.5e-9;
    centralq=30
    nq=70
    perc=100
    step=0.9
    itercg=5
    iter_end=3
    smoothf=0
    smoothi=0
    testadj=0
    filtout=0
    restart=1
    LI=1
    t0=1.85
    clip=63 #clip corresponding to perc=100
    norm=1
    nw=21
    fpeak=25
    nw=0
    dtres=0.008
    ntres=875

else 
    PROGRAM=donothing
fi

scale=1.0
CDPMIN=1000
DXCDP=1
CDPMAX=1000
reject1=-8468,-8293,-8118,-7943,-7768,-7593,-7418,-7243,-7068
accept1=-15993,-15818,-15643


if [ $RADONFORW = 'n' ]; then
    PROGRAM="skipforward"
fi

############################*****
perc=100

cp $FILE $FILETEMP

if [ $OPTIONGAP = 'y' ]; then
    suwind key=offset abs=1 min=1500 max=14000 < $FILETEMP > $FILETEMP2  \
    reject=$reject1 accept=$accept1 
    Xsetntr  $FILETEMP2
    cp $FILETEMP2 $FILETEMP
    cp $FILETEMP  $FILEGAP

    $PLOTX perc=$perc < $FILETEMP &
    
fi


if [ $SETNTR = 'y' ]; then 
    Xsetntr $FILETEMP
fi

if [ $FILT = 'y' ]; then
    sufilter f=$F amps=$AMPS < $FILETEMP > $FILETEMP2;
    cp  $FILETEMP2 $FILETEMP
fi

# Save offset  for inverse radon transform
if [ $GETH = 'y' ]; then
    sugethw key=offset output=geom < $FILE > $offsetfile    
fi

if [ $TAPER = 'y' ]; then
    sutaper < $FILETEMP > $FILETEMP2; cp $FILETEMP2 $FILETEMP
fi

if [ $RESAMPLE = 'y' ]; then
    suresamp < $FILETEMP dt=$dtres nt=$ntres > $FILETEMP2
    cp $FILETEMP2 $FILETEMP
    cp $FILETEMP2 $FILERESAMP
fi


case $PROGRAM in
suradonsolver*)
    $PLOTX < $FILETEMP &
	
    suradonsolver < $FILETEMP verbose=$verbose par=$par itercg=$itercg iter_end=$iter_end solver=$solver rtmethod=$rtmethod  depth=$depth eps2=$eps2 eps1=$eps1 eps=$eps testadj=0  nq=$nq qmin=$qmin norm=$norm nmofactor=1 smute=3.0  step=0.95 factor=$factor modelfile=$FILERAD  quantil=1 fmax=$fmax > $FILEREC

    $PLOTX clip=$clip < $FILEREC title="Reconstructed data from suradonsolver " &

    
;;
suradonwtcgls_tfd*)
    $PLOTX < $FILETEMP &
	
    suradonwtcgls_tfd < $FILETEMP verbose=$verbose par=$par itercg=$itercg iter_end=$iter_end solver=$solver rtmethod=$rtmethod  depth=$depth eps2=$eps2 eps1=$eps1 eps=$eps testadj=0  nq=$nq qmin=$qmin norm=$norm nmofactor=1 smute=3.0  step=0.95 factor=$factor modelfile=$FILERAD  quantil=1 > $FILEREC

    $PLOTX clip=$clip < $FILEREC title="Reconstructed data from suradonwtcgls_tfd " &
;;
suradontd1*)
    suradontd1 eps1=$eps1 eps2=$eps2 iter_end=$iter_end nq=$nq itercg=$itercg eps=$eps \
    step=$step  smooth=0 testadj=$testadj verbose=$verbose par=$PAR pervmin=$pervmin \
    dperv=$dperv modelfile=$FILERAD centralq=$centralq norm=$norm nw=$nw fpeak=$fpeak \
    filtout=$filtout restart=$restart LI=$LI t0=$t0 < $FILETEMP > $FILEREC
;;
skipforward*)
echo "Skipping forward model"
;;
esac



$PLOTR perc=$perc < $FILERAD title="Radon transform"  &
$PLOTX clip=$clip < $FILEREC title="Reconstructed data from ${PROGRAM} " &

case $PROGRAM in
suradontd1*)
    if [ $RESAMPLE = 'y' ]; then
	suradontdi0 modelfile=$FILERAD2 vgridfile="vgrid" datafile=$FILERESAMP  \
	offsetfile=$offsetfile > $FILEREC2
	suresamp < $FILEMULT dt=0.004 nt=1751 > $FILETEMP
	cp $FILETEMP $FILEMULT
    else
	suradontdi0 modelfile=$FILERAD2 vgridfile="vgrid" datafile=$FILE  \
	offsetfile=$offsetfile > $FILEREC2
    fi
;;
*)
suradoninv $FILE $FILERAD2 fmax=$fmax offsetfile=$offsetfile par=$par nq=$nq nmofactor=1 smute=3.0 > $FILEREC2    
;;
esac

sumixgathers  $FILEGAP $FILEREC2 | susort +offset > $FILEMIX
sugain scale=$scale < $FILEREC2 > $FILETEMP ; cp $FILETEMP $FILEREC2
suadapdiff $FILE $FILEMIX op=diff > $FILERES

$PLOTX clip=$clip < $FILEREC2 title="interpolated" &    
$PLOTX clip=$clip < $FILEMIX title="interpolated" &    
$PLOTX clip=$clip < $FILERES  title="residuals" &

exit 0  


































