#! /bin/sh
# Xradon --- Example of interpolation with high resolution radon.
######################################################################
# This example needs sudata1 generated with Xsusyn0
# No extra files are needed.
# method 1 and 2 stands for Usual Radon and High resolution RT.
# First the header of full offset data are saved in file=headers 
# and offset in sudata1.off
# The sudata1.off file is  used by suhrrti to create data at given offsets 
# from the model.
# The headers file is used after suhrrti to put back the header.
# The suwind is used to create gaps that are filled with suhrrtf and suhrrti
# Main purpose of the program is to compare gap filling capabilities of
# HRRT (method=2) with the usual RT (method=1).
# If you change the data check the values at the beginning.
#######################################################################
# Author: Daniel Trad- March 10/99


set -x
NT=512 
NH=111
NP=150
DT=4000
VNMO=2600,2800,3000,3200,3400
TNMO=0,0.5,1,1.5,2

FP=0
DQ=2
HBOX=400
WBOX=350
MIN=500
MAX=15000


FILE=sucdps2b

FILENMO=sucdps2nmo
FILERAD=sucdps2radCU
FILEREC=sucdps2recCUm
FILEOFF=sucdps2off
FILERADOFF=sucdps2radoff
FILERAD2=sucdps2radbCUm
FILEREC2=sucdps2recbCUm
FILEOFF2=sucdps2off2  # Final offset in which data will be resampled 

#NMO in original data
sunmo tnmo=$TNMO vnmo=$VNMO < $FILE > $FILENMO
#suxwigb key=offset title="NMO corrected data" < sudata1nmo &


# Save offset  for inverse radon transform
sugethw key=offset output=geom < $FILE > $FILEOFF
#suxwigb < $FILENMO title="NMO corrected data"  key=offset wbox=550 hbox=650 & 

#Create Gaps           //fprintf(stderr,"alfanum=%e,alfaden=%e\n",alfanum,alfaden);
#suwind abs=1 key=offset min=0 max=900 < $FILENMO > pp
#sushw key=ntr a=68 < pp  > $FILENMO
#suxwigb < $FILENMO  key=offset hbox=$HBOX wbox=$WBOX &
#suaddnoise < $FILEGAP > pp sn=10
#cp pp $FILEGAP
NITER=5
#Forward  Radon transform
#suhrrtf method=3 eps1=1 iter_end=$NITER qmin=-1.5e-7 nq=150 freq=60 rtmethod=2 costflag=1 itercg=20 eps=0 norm=1 eps2=1e-2 step=.5 < $FILENMO  > $FILERAD 
sugethw key=f2 output=binary < $FILERAD > $FILERADOFF
xgraph d1=1 style=normal n=$NITER x1beg=0 x1end=$NITER < Jtottemp &
# method 2 eps1=3 eps=1e-5 iter_end=5
# method 2 eps1=10 eps=1e-15 iter_end=5
# method 7 eps1=10 eps=1e-7 iter_end=10
# method 4 eps1=1 eps=1e-5 iter_end=10

#suxwigb < $FILERAD   key=f2 wbox=550 hbox=650 &
##########
sumute < $FILERAD  key=f2 xmute=-.4e-7,-0.4e-7,0.5e-7,.5e-7 tmute=0,2,2,0 below=1 > $FILERAD2
#sumute < pp  key=f2 xmute=-1e-7,.5e-7,.6e-7,1e-7,1.4e-7,2e-7  tmute=2.0,2.0,1.4,.8,.5,.4  below=1 > ppp
#cp ppp $FILERAD2
################
#sumute < pp > $FILERAD2 key=f2 xmute=-2e-7,-2e-7,-1e-7,-1e-7,8e-7 tmute=0,2.1,2.1,0,0 below=0
#cp $FILERAD $FILERAD2
suxwigb < $FILERAD2  perc=99  key=f2 wbox=550 hbox=650 &
#Inverse Radon Transformr

suhrrti rtmethod=2 offsetfile=$FILEOFF2  fmax=50 < $FILERAD2  > $FILEREC
#cp $FILEREC $FILEREC2

#NMO in original data
sunmo tnmo=$TNMO vnmo=$VNMO invert=1 < $FILEREC  > $FILEREC2 
#suxmovie title="NMO corrected data" < sudata1nmo &

suxwigb < $FILEREC2   key=offset  wbox=550 hbox=650  &

#binary file with radon parameter
#sugethw key=f2 output=binary < $FILERAD2 > $FILERADOFF  
exit 0  






















