#! /bin/sh
# Xradon --- Comparison of Radon methods.
######################################################################
# Example: real  sucdps2
# 
#######################################################################
# Author: Daniel Trad- November 1999

# Some shortcuts for plots
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650"
HBOX=400
WBOX=350


set -x
NT=512 
NH=111
NP=150
DT=4000
VNMO=2600,2800,3000,3200,3400
TNMO=0,0.5,1,1.5,2

FP=0
DQ=2
HBOX=400
WBOX=350
MIN=500
MAX=15000

OPTIONSETNTR='n'
OPTIONNMO='n'
OPTIONGETH='n'
OPTIONFILT='y'

FILEVEL=stkvel.cdps1
FILE=sucdps2
FILEN=sucdps2CGCM
FILENMO=$FILE'nmo'
FILEGAP=$FILE'gap'
FILEOFF=$FILE'off'
FILERAD=$FILEN'rad'
FILEREC=$FILEN'rec'
FILERADOFF=$FILEN'radoff'
FILERAD2=$FILEN'radb'
FILEREC2=$FILEN'recb'
FILEOFF2=$FILEOFF # Final offset in which data will be resampled 
# NMO
SMUTE=3;
# PASS BAND FILTER
F=1,10,70,80
AMPS=0,1,1,0

case $OPTIONSETNTR in
y*)
ntr=`surange < $FILE | sed 1q | sed 's/traces://'`
cp $FILE pp
sushw key=ntr a=$ntr < pp > $FILE 
;;
esac

case $OPTIONFILT in
y*)
sufilter f=$F amps=$AMPS < $FILE > pp; cp pp $FILE
;;
esac


#NMO in original data
#sunmo tnmo=$TNMO vnmo=$VNMO < $FILE > $FILENMO
case $OPTIONNMO in
y*)
sunmo par=$FILEVEL < $FILE > $FILENMO 
$PLOTX < $FILENMO &
;;
esac

# Save offset  for inverse radon transform
case $OPTIONGETH in
y*)
sugethw key=offset output=geom < $FILE > $FILEOFF
;;
esac

NITER=5
#Forward  Radon transform
suhrrtf method=10 eps1=1 iter_end=$NITER qmin=-0.5e-7 nq=150 freq=60 rtmethod=2 costflag=0 itercg=15 eps=1e-1 norm=1 step=.5 < $FILENMO  > $FILERAD 
sugethw key=f2 output=binary < $FILERAD > $FILERADOFF

suxwigb < $FILERAD  perc=99  key=f2 wbox=550 hbox=650 &

#Inverse Radon Transformr
suhrrti rtmethod=2 offsetfile=$FILEOFF  fmax=60 < $FILERAD  > $FILEREC


#NMO in original data
sunmo par=$FILEVEL  invert=1 < $FILEREC  > $FILEREC2 
suxwigb < $FILEREC2   key=offset  wbox=550 hbox=650  &

exit 0  






















