#! /bin/sh
# Xradon --- Example of interpolation with high resolution radon.
######################################################################
# This example needs sudata1 generated with Xsusyn0
# No extra files are needed.
# method 1 and 2 stands for Usual Radon and High resolution RT.
# First the header of full offset data are saved in file=headers 
# and offset in sudata1.off
# The sudata1.off file is  used by suhrrti to create data at given offsets 
# from the model.
# The headers file is used after suhrrti to put back the header.
# The suwind is used to create gaps that are filled with suhrrtf and suhrrti
# Main purpose of the program is to compare gap filling capabilities of
# HRRT (method=2) with the usual RT (method=1).
# If you change the data check the values at the beginning.
#######################################################################
# Author: Daniel Trad- March 10/99


set -x
NT=640
NH=26
NP=170
DT=800


FP=0
DQ=2
HBOX=400
WBOX=350
FILE=suradar3
FILERAD=suradar3rad
FILERADS=suradar3rads
FILEREC=suradar3rec
FILERECS=suradar3recs
FILEOFF=suradar3off
FILERADOFF=suradar3radoff

FILERAD2=suradar3radb
FILERAD2S=suradar3radbs
FILEREC2=suradar3recb
FILEREC2S=suradar3recbs
#FILEOFF2=suradar2off  # Final offset in which data will be resampled 

# Save offset  for inverse radon transform
sugethw key=offset output=geom < $FILE > $FILEOFF
#suxwigb < $FILE   key=offset wbox=550 hbox=650 & 
#Create Gaps
#suwind  tmin=0 tmax=512 < $FILE > pp
 #sushw key=ntr a=$NH < pp  > $FILE2
#suxwigbq < $FILEGAP  key=offset hbox=$HBOX wbox=$WBOX &


#Forward  Radon transform
#suhrrtf method=3 eps1=3  qmin=0 nq=$NP freq=500 rtmethod=1 costflag=0 itercg=50 iter_end=7 eps=1e-5 eps2=1e-4  norm=10 < $FILE  > $FILERAD 


# For gap example: 
# method=2 eps1=0.1 iter_end=10  itercg=25 eps=1e-10 
# method=10 eps=1e-4 method=7 eps=1e-7
# method=4 eps=1e-4 

suxwigb < $FILERAD   key=f2 wbox=550 hbox=650 &
sumute < $FILERAD  key=f2 xmute=0,4e-3,12e-3 tmute=0.1,0.09,0 taper=5 below=0 > pp
sumute <  pp key=f2 xmute=0,4e-3,13e-3 tmute=0.3,0.27,0 taper=5 below=1 > $FILERAD2 
#suop2  $FILERAD ppp op=diff  > pp   

#sumute < ppp key=f2 xmute=-2e-4,2e-4,2e-4,9e-4 tmute=0,0,2,2 taper=5  below=1 > $FILERAD2
#sumute < ppp key=f2 xmute=6e-4,9e-4 tmute=2,2 taper=5  below=0 > $FILERAD2
#sumute < pp key=f2 xmute=4e-4,6e-4 tmute=2,1.6 taper=5  below=1 > $FILERAD2
#cp $FILERAD $FILERAD2
suxwigb < $FILERAD2   key=f2 wbox=550 hbox=650 &
#Inverse Radon Transform
suhrrti rtmethod=1 offsetfile=$FILEOFF  fmax=500 < $FILERAD2  > $FILEREC2
suxwigb < $FILEREC2   key=offset  wbox=550 hbox=650  &

sustrip < $FILERAD > $FILERADS outpar=/home/dtrad/radon/param
sustrip < $FILEREC > $FILERECS outpar=/home/dtrad/radon/param
sustrip < $FILERAD2 > $FILERAD2S outpar=/home/dtrad/radon/param
sustrip < $FILEREC2 > $FILEREC2S outpar=/home/dtrad/radon/param
#binary file with radon parameter  
#cp myfile $FILERADOFF

exit 0  
















