#! /bin/sh
# shell for multiple attenuation by RT along a line
# June 16 -2001
# Daniel Trad - UBC

set -x

METHOD="${1}"

PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=90"

#NAME=misscn_red_gain_cdp # reduced data set with all cdps
NAME=line159ar # Complete data
NAME=cdp1500char
FILE=$NAME'.su'
FILEOUT=$NAME'.demul.su'
PAR=stkvel.line159ar.su
PAR=stkvel.line159ar.cte.su

CDPMIN=1500
CDPMAX=1500
dxcdp=1
ntrmax=100000000   # For fast tests use only few traces.

######################################
# Radon parameters

#t0=1.5;
t0=2;
VERBOSE=1
mute=0        
t0mute=6
parmute=-5e-8
smute=1.6

PLOTOPT='XPLOT3'
LABELT="time(sec)" 
LABELO="Offset(m)"
if [ $METHOD = "SOL" ]; then
#parmute=1.5e-9
suradonline < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=30 iter_end=3 eps2=1e-1 eps1=1e-1 nq=110 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 buffer=$buffer t0=$t0 smute=$smute mute=$mute  parmute=$parmute qmin=-3.5e-8 factor=1.2 fmax=120 solver="$2" t0mute=$t0mute nmofactor=1 > $FILEOUT
else
itercg=100
suradoncgfft_tfd2 < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=$itercg iter_end=3 eps2=5e-2 eps1=5e-2 nq=110 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 buffer=$buffer t0=$t0 smute=$smute mute=$mute  parmute=1.5e-9 qmin=-3.5e-8 factor=1.5 fmax=80  t0mute=$t0mute  > $FILEOUT
fi

$PLOTX < $FILEOUT  title=$label  &

################################################################

case $PLOTOPT in
    PSPLOT*)
    ;;

    XPLOT2*)
    
    cdp=$CDPMIN
      
    while [ $cdp -le $CDPMAX ]
    do
    title=$cdp' CDP'
    suwind key=cdp min=$cdp max=$cdp  < $FILEOUT | $PLOTX  title=$title &
    suwind key=cdp min=$cdp max=$cdp  < model.su | $PLOTR  title=$title &

cdp=`bc -l <<END
		$cdp + $DXCDP
END`


    done
    ;;
esac






 




































































































