#! /bin/sh
# Xradon --- Hyperbolic Radon Transform.
######################################################################
# Example: real  sucdps2, sumiss2
# 
#######################################################################
# Author: Daniel Trad- November 1999

# Some shortcuts for plots
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650"
HBOX=400
WBOX=350

set -x
NT=512 
NH=111
NP=150
DT=4000

VNMO=1500,2000,3000
TNMO=0.5,1,2

FP=0
DQ=2
HBOX=400
WBOX=350
MIN=500
MAX=15000


FILE=cdps2.mute.su

if [ $1 -eq 1 ] ; 
then FILEN=$FILE'';  prec=1 ; FILERECORD=$FILEN'log';
fi

if [ $1 -eq 2 ] ; 
then FILEN=$FILE'';  prec=2 ; FILERECORD=$FILEN'log';
fi

FILETEMP=pp
FILETEMP2=ppp
FILENMO=$FILE'nmo'
FILEGAP=$FILE'gap'
FILEOFF=$FILE'off'
FILERAD=$FILEN'rad'
FILEREC=$FILEN'rec'
FILERADOFF=$FILEN'radoff'
FILERAD2=$FILEN'radb'
FILEREC2=$FILEN'recb'
FILEOFF2=$FILEOFF'2'  # Final offset in which data will be resampled 

# Options
OPTIONGAP='n'
OPTIONSETNTR='y'
OPTIONGETH='y'
OPTIONFILT='n'
OPTIONAGC='n'
OPTIONRAD='n'
OPTIONINT='y'
OPTIONMUTE='n'
OPTIONREC='n'
OPTIONRES='n'

# PASS BAND FILTER
F=1,10,70,80
AMPS=0,1,1,0
# RADON (see suhrrtf for more details)
METHOD=8 
dperv=0.2;
pervmin=20;
EPS1=1e-1  # Variance of the noise
EPS2=1e-1 
ITER_END=0 ; # External iterations 
QMIN=2e-7  # Min q
QMAX=12e-7
QMIN=-300
QMAX=300
NQ=20      # NP traces
FMAX=70     # max freq to compute
RTMETHOD=3 # 1=LRT 2=PRT 3=HRT
COSTFLAG=0 # =1 PLOT COST FUNCTIONS (SLOWER)
ITERCG=5  # CG ITERATIONS
EPS=0.001      # =0 FOR METHOD 2 
NORM=1     # L1 NORM
STEP=0.7  # Step less 1
THRES=0.5 
TESTADJ=0
VERBOSE=0
SMOOTH=1
perc=90
eps=0.001
itercg=$2
iter_end=$3
step=1


TVEL=0.01741,0.1323,0.2368,0.3203,0.4491,0.5431,0.5675,0.6859,0.8495,1.017,1.128,1.233,1.271,1.4,1.518,1.636,1.737,1.898,2.037,2.152,2.166
VEL=2412,2446,2520,2600,2691,2736,2748,2822,3004,3158,3181,3306,3363,3517,3545,3517,3454,3329,3204,3084,3073

cp $FILE $FILETEMP

case $OPTIONGAP in
y*)
suwind key=offset abs=1 min=200 max=700 < $FILETEMP > $FILETEMP2
cp $FILETEMP2 $FILETEMP
cp $FILETEMP  $FILEGAP
$PLOTX perc=$perc < $FILETEMP &
;;
esac


case $OPTIONSETNTR in
y*)
ntr=`surange < $FILETEMP | sed 1q | sed 's/traces://'`
sushw key=ntr a=$ntr < $FILETEMP > $FILETEMP2
cp  $FILETEMP2 $FILETEMP
;;
esac

case $OPTIONFILT in
y*)
sufilter f=$F amps=$AMPS < $FILETEMP > $FILETEMP2;
cp  $FILETEMP2 $FILETEMP
;;
esac


# Save offset  for inverse radon transform
case $OPTIONGETH in
y*)
sugethw key=offset output=geom < $FILE > $FILEOFF
;;
esac

case $OPTIONRAD in
y*)
#Forward  Radon transform
suradtd method=$METHOD  eps1=$EPS1 eps2=$EPS2 iter_end=$ITER_END qmin=$QMIN qmax=$QMAX nq=$NQ freq=$FMAX rtmethod=$RTMETHOD costflag=$COSTFLAG itercg=$ITERCG eps=$EPS norm=$NORM step=$STEP thres=$THRES smooth=$SMOOTH testadj=$TESTADJ verbose=$VERBOSE vel=$VEL tvel=$TVEL pervmin=$pervmin dperv=$dperv < $FILETEMP  > $FILERAD
$PLOTR perc=$perc < $FILERAD &
;;
esac

case $OPTIONINT in
y*)
#Forward  Radon transform
suradint method=0  eps1=$8 eps2=$EPS2 iter_end=$iter_end qmin=$QMIN qmax=$QMAX nq=$NQ freq=$FMAX rtmethod=$RTMETHOD costflag=$COSTFLAG itercg=$itercg eps=$eps norm=$9 step=$step thres=$THRES smooth=$SMOOTH testadj=$TESTADJ verbose=$VERBOSE vel=$VEL tvel=$TVEL pervmin=$pervmin dperv=$dperv modelfile=$FILERAD precond=1 prec=$prec  alum=$4 blum=$5 clum=$6 < $FILETEMP  > $FILEREC qq

echo "prec=$prec" > $FILERECORD
#echo "Original data" >> $FILERECORD

#$PLOTX perc=$perc < $FILERAD title="Modified Radon transform" &
#$PLOTX perc=$perc < $FILE  title="Original data"  2>> $FILERECORD &
echo "Interpolated data" >> $FILERECORD
$PLOTX perc=$perc < $FILEREC title="Interpolated data -prec=$prec " 2>> $FILERECORD &
;;
esac

#Inverse Radon Transformr
case $OPTIONREC in
y*)
suradtdi method=$METHOD rtmethod=$RTMETHOD fmax=$FMAX offsetfile=$FILEOFF2 \
smooth=0 vel=$VEL tvel=$TVEL verbose=0 < $FILERAD > $FILEREC
$PLOTX perc=$perc < $FILEREC title="Residuals -prec=$prec "  2>> $FILERECORD &

#cat $FILERECORD
;;
esac




exit 0  






















