#! /bin/sh
# Xradon --- Hyperbolic Radon Transform.
######################################################################
# Example: real  sucdps2, sumiss2
# 
#######################################################################
# Author: Daniel Trad- November 1999

# Some shortcuts for plots
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650"
HBOX=400
WBOX=350


set -x
NT=512 
NH=111
NP=150
DT=4000

VNMO=1500,2000,3000
TNMO=0.5,1,2

FP=0
DQ=2
HBOX=400
WBOX=350
MIN=500
MAX=15000


FILE=sumiss2sg
FILEN=$FILE
FILENMO=$FILE'nmo'
FILEGAP=$FILE'gap'
FILEOFF=$FILE'off'
FILERAD=$FILEN'rad'
FILEREC=$FILEN'rec'
FILERADOFF=$FILEN'radoff'
FILERAD2=$FILEN'radb'
FILEREC2=$FILEN'recb'
FILEOFF2=$FILEOFF # Final offset in which data will be resampled 

# Options
OPTIONSETNTR='y'
OPTIONGETH='y'
OPTIONFILT='y'
OPTIONAGC='y'
OPTIONRAD='n'
OPTIONMUTE='n'
OPTIONREC='y'
OPTIONRES='y'

# PASS BAND FILTER
F=1,10,70,80
AMPS=0,1,1,0
# RADON (see suhrrtf for more details)
METHOD=7 # 
EPS1=1  # Variance of the noise
ITER_END=0 ; # External iterations 
QMIN=-2e-4  # Min q
QMAX= 2e-4
NQ=120      # NP traces
FMAX=50     # max freq to compute
RTMETHOD=1 # 1=LRT 2=PRT 3=HRT
COSTFLAG=0 # =1 PLOT COST FUNCTIONS (SLOWER)
ITERCG=10  # CG ITERATIONS
EPS=0      # =0 FOR METHOD 2 
NORM=1     # L1 NORM
STEP=0.9  # Step less 1
THRES=0.5 
FACTOR=6
SMOOTH=0

case $OPTIONSETNTR in
y*)
ntr=`surange < $FILE | sed 1q | sed 's/traces://'`
cp $FILE pp
sushw key=ntr a=$ntr < pp > $FILE 
;;
esac

case $OPTIONFILT in
y*)
sufilter f=$F amps=$AMPS < $FILE > pp; cp pp $FILE
;;
esac


# Save offset  for inverse radon transform
case $OPTIONGETH in
y*)
sugethw key=offset output=geom < $FILE > $FILEOFF
;;
esac

case $OPTIONRAD in
y*)
#Forward  Radon transform
suradtd method=$METHOD  eps1=$EPS1 iter_end=$ITER_END qmin=$QMIN qmax=$QMAX nq=$NQ freq=$FMAX rtmethod=$RTMETHOD costflag=$COSTFLAG itercg=$ITERCG eps=$EPS norm=$NORM step=$STEP thres=$THRES smooth=$SMOOTH factor=$FACTOR < $FILE  > $FILERAD 
;;
esac

suxwigb < $FILERAD  key=f2 wbox=550 hbox=650 &

#Inverse Radon Transformr
case $OPTIONREC in
y*)
suradtdi rtmethod=$RTMETHOD fmax=$FMAX offsetfile=$FILEOFF2 \
smooth=$SMOOTH < $FILERAD > $FILEREC
 
#sufilter < $FILEREC f=$F amps=$AMPS > $FILEREC
;;
esac


suxwigb < $FILEREC   key=offset  wbox=550 hbox=650  &

exit 0  






















