#! /bin/sh
# Xradon_demul_cdp1000 --- Multiple attenuation with  Radon Transform.
######################################################################
# Author: Daniel Trad- May 2001

# Some shortcuts for plots
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650"

set -x

METHOD='SOL'
#METHOD='TFD'
#METHOD='HRF'
#METHOD='TD'

RADONFORW='y'
REMOVEMUL='n'


sufix=${METHOD}
echo $METHOD

if [ ${METHOD} = 'SOL' ]; then
    sufix="${1}"
fi

#FILE=cdp1000.su; clip=17   #clip corresponding to perc=97
FILE=seisdata1.su; clip=95  #clip corresponding to perc=97

FILEN=$FILE
FILETEMP=pp
FILETEMP2=ppp
FILEOFF=$FILE'off'
FILERAD=${FILEN}'rad_'${sufix}
FILEMULT=${FILEN}'mul_'${sufix}
FILEPRIM=${FILEN}'pri_'${sufix}
FILERAD2=${FILEN}'radmul_'${sufix}
FILEREC=$FILEN'rec'${sufix}
FILERESAMP=$FILE'resamp'${sufix}
RESAMPLE='n'
REDAPER='n'
PAR="stkvel.misscn3b.su"
par=$PAR

# Options
SETNTR='y'
GETH='y'
FILT='n'
TAPER='n'

# PASS BAND FILTER
F=1,10,70,80
AMPS=0,1,1,0
# RADON
#***Freq############################ 

VERBOSE=1
fold=1
buffer=10; 
iter_end=4
sinc=0;
parmute=3e-9
parmute=22e-9
nq=100
under=0.999
over=1.001
qmin=-5e-4
factor=1 # Full gather
fmax=4

if [ $REDAPER = 'y' ]; then
    factor=0.6 #limited gather
    qmin=-5e-4
    nq=50
fi

cp $FILE $FILETEMP

if [ $METHOD = 'SOL' ]; then
    iter_end=3
    eps1=1e-2
    eps2=1e-2
    norm=0
    eps=1e-7
    rtmethod=1
    itercg=25
    verbose=0
    depth=1000
    PROGRAM=suradonsolver
    solver="$1"
elif [ $METHOD = 'TFD' ]; then
    iter_end=3
    eps1=1e-2
    eps2=1e-2
    #factor=1.5
    norm=0
    eps=1e-7
    rtmethod=1
    itercg=15
    iter_end=3
    verbose=0
    depth=1000
    PROGRAM=suradonwtcgls_tfd
    solver="$1"
elif [ $METHOD = 'TD' ]; then
    eps1=1e-3
    eps2=1e-3
    PROGRAM=suradontd0
    eps=0.01
    dperv=0.03;
    dperv=0.03;
    pervmin=0.5e-9;
    centralq=30
    nq=70
    perc=100
    step=0.9
    itercg=15
    iter_end=3
    smoothf=0
    smoothi=0
    testadj=0
    filtout=0
    restart=1
    LI=1
    t0=1.85
    clip=63 #clip corresponding to perc=100
    norm=1
    nw=21
    fpeak=25
    nw=0
    dtres=0.008
    ntres=875

else 
    PROGRAM=donothing
fi

scale=1.1
CDPMIN=1000
DXCDP=1
CDPMAX=1000

if [ $RADONFORW = 'n' ]; then
    PROGRAM="skipforward"
fi

############################*****
perc=99



if [ $SETNTR = 'y' ]; then 
    Xsetntr $FILETEMP
fi

if [ $FILT = 'y' ]; then
    sufilter f=$F amps=$AMPS < $FILETEMP > $FILETEMP2;
    cp  $FILETEMP2 $FILETEMP
fi

# Save offset  for inverse radon transform
if [ $GETH = 'y' ]; then
    sugethw key=offset output=geom < $FILE > $FILEOFF    
fi

if [ $TAPER = 'y' ]; then
    sutaper < $FILETEMP > $FILETEMP2; cp $FILETEMP2 $FILETEMP
fi

if [ $RESAMPLE = 'y' ]; then
    suresamp < $FILETEMP dt=$dtres nt=$ntres > $FILETEMP2
    cp $FILETEMP2 $FILETEMP
    cp $FILETEMP2 $FILERESAMP
fi


case $PROGRAM in
suradonsolver*)
    $PLOTX < $FILETEMP &
	
    suradonsolver < $FILETEMP fmax=$fmax verbose=$verbose par=$par itercg=$itercg iter_end=$iter_end solver=$solver rtmethod=$rtmethod  depth=$depth eps2=$eps2 eps1=$eps1 eps=$eps testadj=0  nq=$nq qmin=$qmin norm=$norm nmofactor=0 smute=3.0  step=0.95 factor=$factor modelfile=$FILERAD  quantil=1 > $FILEREC

    #$PLOTX perc=$perc < $FILEREC title="Reconstructed data from suradonsolver " &

;;
suradonwtcgls_tfd*)
    $PLOTX < $FILETEMP &
	
    suradonwtcgls_tfd < $FILETEMP fmax=$fmax verbose=$verbose par=$par itercg=$itercg iter_end=$iter_end solver=$solver rtmethod=$rtmethod  depth=$depth eps2=$eps2 eps1=$eps1 eps=$eps testadj=0  nq=$nq qmin=$qmin norm=$norm nmofactor=1 smute=3.0  step=0.95 factor=$factor modelfile=$FILERAD  quantil=1 > $FILEREC

    $PLOTX clip=$clip < $FILEREC title="Reconstructed data from suradonwtcgls_tfd " &

;;

suradontd0*)
    suradontd0 eps1=$eps1 eps2=$eps2 iter_end=$iter_end nq=$nq itercg=$itercg eps=$eps \
    step=$step  smooth=0 testadj=$testadj verbose=$verbose par=$PAR pervmin=$pervmin \
    dperv=$dperv modelfile=$FILERAD centralq=$centralq norm=$norm nw=$nw fpeak=$fpeak \
    filtout=$filtout restart=$restart LI=$LI t0=$t0 < $FILETEMP > $FILEREC
;;
skipforward*)
echo "Skipping forward model"
;;
esac



$PLOTR perc=$perc < $FILERAD title="Modified Radon transform"  &
$PLOTX perc=$perc < $FILEREC title="Reconstructed data from suradontoep " &


if [ $REMOVEMUL = 'y' ]; then
    # If picks have been already done use directly sumute, otherwise use Xmuterad
    Xmuterad $FILERAD $FILERAD2
    
    #sumutepar < $FILERAD left=0 > $FILERAD2
    #sumute < $FILERAD key=f2 xfile=xfileb tfile=tfileb nmute=4 below=0  > $FILERAD2
    case $PROGRAM in
    suradontd0*)
    if [ $RESAMPLE = 'y' ]; then
	suradontdi0 modelfile=$FILERAD2 vgridfile="vgrid" datafile=$FILERESAMP  \
	offsetfile=$FILEOFF > $FILEMULT
	suresamp < $FILEMULT dt=0.004 nt=1751 > $FILETEMP
	cp $FILETEMP $FILEMULT
    else
	suradontdi0 modelfile=$FILERAD2 vgridfile="vgrid" datafile=$FILE  \
	offsetfile=$FILEOFF > $FILEMULT
    fi
    
    ;;
    *)
    suradoninv $FILE $FILERAD2 rtmethod=$rtmethod fmax=$fmax par=$par nq=$nq nmofactor=0 smute=3.0  > $FILEMULT    
    ;;
    esac
    #sugain scale=$scale < $FILEMULT > $FILETEMP ; cp $FILETEMP $FILEMULT
    #suop2 $FILE $FILEMULT op=diff > $FILEPRIM
    suadapdiff $FILE $FILEMULT > $FILEPRIM

    $PLOTX perc=$perc < $FILEPRIM title="Primaries" &    
    $PLOTX perc=$perc < $FILEMULT title="Multiples" &

fi


exit 0  


































