#! /bin/sh
# shell for dip filter
# Daniel Trad - UBC - CDSST 
set -x

echo "Xremove_nonzeroapex"

date 1>&2

PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=90"


NAME=$1

FILEIN=$NAME'.su'
FILENMO=$NAME'nmo.su'
FILEDIP=$NAME'dipf.su'
FILEOUT=$NAME'inmo.su'


sunmo < $FILEIN vnmo=1900,2500 tnmo=0,1.2 > $FILENMO
#sunmo < $FILEIN vnmo=3500,3500 tnmo=0,2 > $FILENMO

# slopes are compute as k/w+bias

slopes=-${2},0,${2}
slopes=-0,${2}
slopes=-${2},0,${3}

bias="${4}"
if [ -z ${4} ]; then
    bias=0
fi

if [ -z ${2} ]; then
    slopes=-0.0005,0,0.0005 
fi

amps=0.0,1,0.0
amps=1,0.0
amps=0.0,1,0.0
#amps=1.0,0,1.0

dx=50
suximage <  $FILENMO perc=97 key=offset title="NMO" &
suspecfk < $FILENMO | suximage perc=97 title="NMO" xbox=600 &

sudipfilt < $FILENMO dx=$dx  bias=$bias amps=$amps slopes=$slopes  > $FILEDIP
suxwigb <  $FILEDIP perc=97 key=offset title="filtered" &
suspecfk < $FILEDIP | suximage perc=97 title="filtered" xbox=600 &
sunmo < $FILEDIP vnmo=1900,2500 tnmo=0,1.2 invert=1 > $FILEOUT

suxwigb <  $FILEOUT perc=97 key=offset title="filtered and inmo" &
suspecfk < $FILEOUT | suximage perc=97 title="filt and iNMO" xbox=600 &

suop2  $FILEIN  $FILEOUT |  suxwigb perc=99 key=offset title="difference" &
#sudipfilt < $FILEIN dx=$dx  amps=$amps slopes=$slopes  | suximage perc=99 &
