#!/bin/sh
# Script to generate the files for Xplotdemult
# Xsuradonline ==> generates files with standard names
# Xrename      ==> rename the files and generates ps files for semblance
# Xplotdemult_cdp1000 ==> creates the final figure
#METHOD="TFD"
#METHOD="SOLcgfft"

set -x

METHOD=HRT
FILEIN1=~/china/line159cr.su
FILEIN2=line159cr.demul.su
cdp=${1} 
FILEN="cdp${cdp}"
. $HOME/shell/lib/libshellsu.sh

FILE1="${FILEN}.su" 
FILE2="${FILEN}.supri_${METHOD}"
FILE3="${FILEN}.sumul_${METHOD}"
FILE4="${FILEN}.surad_${METHOD}"
FILE5="arrow-4.ps"
FILE6="${FILEN}.suradmul_${METHOD}"
FILE7="${FILEN}.su_metric.1000.ps"
FILE8="${FILEN}.supri_${METHOD}.1000.ps"
FILE9="${FILEN}.sumul_${METHOD}.1000.ps"

suwind < $FILEIN1 key=cdp min=$cdp max=$cdp > $FILE1
Xsetntr $FILE1
cp $FILEIN2 $FILE2

if [ $METHOD = "HRT" ]; then
    suadapdiff $FILE1 $FILE2 > $FILE3
    #sushw key=f1 a=1.5 < multiples.su > $FILE3
else
    sunmo invert=1 <  multiples.su > $FILE3 par=stkvel.misscn.su
    feet2meter_offset $FILE3
    sushw key=cdp a=$cdp < $FILE3 > $FILE3'temp'
    mv $FILE3'temp' $FILE3
fi

cp model.su $FILE4
cp mutedmodel.su $FILE6


Velan1 $FILE1 ${cdp} ${cdp} 1 0.03 "(f)"
Velan1 $FILE2 ${cdp} ${cdp} 1 0.03 "(g)"
Velan1 $FILE3 ${cdp} ${cdp} 1 0.03 "(h)"










