#! /bin/sh
# Run GBmod with Xwindow Graphics
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL Xdemo
#------------------------------------------------


datadir=./
modelfile=${datadir}model.data

##### Built salt dome model (Figure 3)

trimodel xmin=0 zmin=0 xmax=8 zmax=4 maxangle=10 \
1       xedge=0.0,8.0 \
	zedge=0.0,0.0 \
	sedge=1.00,1.00 \
2       xedge=0.0,1.0,2.0,3.0,8.0 \
        zedge=0.2,0.23,0.25,0.26,0.27 \
        sedge=1.00,1.00,1.00,1.00,1.00 \
3       xedge=0.0,1.0,1.0,1.0,1.5 \
        zedge=1.0,1.0,2.0,3.0,4.0 \
        sedge=0.40,0.40,0.30,0.20,0.10 \
4       xedge=1.0,1.5,8.0 \
	zedge=1.0,1.3,2.2 \
	sedge=0.40,0.40,0.40 \
5       xedge=1.0,1.5,8.0 \
	zedge=2.0,2.4,3.3 \
	sedge=0.30,0.30,0.30 \
6       xedge=0.0,1.5,8.0 \
	zedge=4.0,4.0,4.0 \
	sedge=0.10,0.10,0.10 \
        sfill=0.1,3.1,0.0,0.0,0.10,0.00,0.00 \
        kedge=1,2,3,4,5,6 \
	>$modelfile

sxplot <$modelfile -geom 650x300+670+0\
        label1="Depth (km)" label2="Distance (km)" \
        title="Salt Model" tricolor=none &


rayendsfile=${datadir}rayends.data
rayfile=${datadir}rays.data

nxz=201 nangle=130 

####   shoot the rays
triray <$modelfile >$rayendsfile xs=3.0 zs=0 \
	rayfile=$rayfile nxz=$nxz krecord=1 \
       	nangle=$nangle fangle=-60 langle=0 \
        refseq=3,1 refseq=1,-1 
xgraph <$rayfile -geom 650x300+670+330 nplot=`cat outpar` n=$nxz \
        x1beg=0 x1end=4 x2beg=0 x2end=8 style=seismic linecolor=7 \
        label1="Depth (km)" label2="Distance (km)" title="Raypaths" &


#### generate and plot common shot record
gbbeam<$rayendsfile \
        bw=0 xg=0,8 zg=0,0 ng=101 lscale=0.8 \
	krecord=1 nt=251 dt=0.032 ft=0 |
xwigb   xbox=670 ybox=660 perc=100 xcur=3.0 \
        n1=251 d1=0.032 f1=0 hbox=300 wbox=650\
        n2=101 d2=0.08 f2=0 title="Common Shot Seismograms" \
        label1="Time (sec)" label2="Distance (km)" grid1=solid &
exit 0
