#! /bin/sh
# Run GBmod with Xwindow Graphics
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL Xdemo
#------------------------------------------------
name="saltdome"
fileout=$name".su"
filestack=$name".stack.su"
data=./
modelfile=${data}model.saltdome

##### Built syncline model (Figure 14)
trimodel xmin=0 zmin=0 xmax=8 zmax=4 maxangle=10 \
1       xedge=0.0,8.0 \
	zedge=0.0,0.0 \
	sedge=1.00,1.00 \
2       xedge=0.0,1.0,2.0,3.0,8.0 \
        zedge=0.2,0.23,0.25,0.26,0.27 \
        sedge=1.00,1.00,1.00,1.00,1.00 \
3       xedge=0.0,1.0,1.0,2.0,2.5 \
        zedge=1.0,1.0,2.0,3.0,4.0 \
        sedge=0.40,0.40,0.30,0.20,0.10 \
4       xedge=1.0,1.5,8.0 \
	zedge=1.0,1.3,2.2 \
	sedge=0.40,0.40,0.40 \
5       xedge=1.0,1.5,8.0 \
	zedge=2.0,2.4,3.3 \
	sedge=0.30,0.30,0.30 \
6       xedge=0.0,1.5,8.0 \
	zedge=4.0,4.0,4.0 \
	sedge=0.10,0.10,0.10 \
        sfill=0.1,3.1,0.0,0.0,0.10,0.00,0.00 \
        kedge=1,2,3,4,5,6 \
	>$modelfile

sxplot < $modelfile -geom 650x300+670+0 \
        label1="Depth (km)" label2="Distance (km)" \
	tricolor=yellow title="Syncline Model"&


set -x
##### Generate Finite-Offset section
fgrel=100

nangle=130 nxz=401 fangle=-65 langle=65
nt=1024 dt=0.004 bw=0 ft=0.0
ng=200
dg=0.03

# dg in meters
dgm=`bc -l <<END
		$dg * 1000
END`

fsimin=0
fsimax=3000
dfsi=40
fsi=$fsimin
rm $fileout
while [ $fsi -le $fsimax ]
do

# calculate position of source in km
       fs=`bc -l <<END
		$fsi / 1000
END`
    echo $fs
# calculate position of first receiver in km
       fgi=`bc -l <<END
		$fsi + $fgrel
END`
       fg=`bc -l <<END
		$fgi / 1000
END`
    echo $fg


#### create zero offset section
triseis <$modelfile  xs=0,8 zs=0,0 xg=0,8 zg=0,0 \
	nangle=$nangle fangle=$fangle langle=$langle \
	kreflect=3 krecord=1 fpeak=20 lscale=0.5 \
	ns=1 fs=$fs ds=0.0 dgds=1 bw=$bw \
        ng=$ng fg=$fg dg=$dg nt=$nt dt=$dt ft=$ft > temp

suaddhead ns=$nt < temp | sushw key=dt a=4000 | sushw key=sx a=$fsi | sushw key=gx a=$fgi b=$dgm > temp2


cat temp2 >> $fileout

#xwigb < temp  n1=$nt d1=$dt f1=$ft x1end=4.5 n2=$ng d2=$dg f2=0 grid1=none perc=100 xcur=1.0 title="common source data" hbox=300 wbox=650 xbox=670 ybox=660 label1="Time (sec)" label2="Offset (km)" &

       fsi=`bc -l <<END
		$fsi + $dfsi
END`

done

suchw< $fileout key1=offset,cdp key2=gx,gx key3=sx,sx  b=1,1 c=-1,1 d=1,2 > temp
mv temp $fileout

zap xgraph
zap xwigb
zap sxplot

susort +cdp < $fileout > pp; mv pp $fileout
sunmo vnmo=1200 < $fileout | sustack key=cdp > $filestack; 
Xsetntr $fileout
Xsetntr $filestack
suximage < $filestack &

exit 0



