#! /bin/sh
# Exercise 1 - Scale book
N1=101
N2=101

susynlv nt=$N1 dt=0.04 ft=0 nx0=1 \
 nxm=$N2 dxm=0.05 fxm=0.0 er=1 ob=1 \
 v00=1.0 dvdz=0.0 dvdx=0.0 smooth=1 \
 ref="0,.5;1.,.5;2.,.8;2.5,1.0;3.0,.8;4.0,.5;5.0,.5" | 
 sushw key=d2 a=.05 > pp

suxwigb < pp &

sugazmig < pp tmig=0 vmig=1 > ppp
suxwigb < ppp &



