#! /bin/sh
# shell for dip filter
# Daniel Trad - UBC - CDSST 
# to obtain the segy words from the file use 
#        sugethw < FILEIN key=sx output=geom | sort | uniq > sxwords
set -x

PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=90"


NAME=$1

FILEIN=$NAME'.su'
FILEOUT=$NAME'.gathers.su'

# slopes are compute as k/w+bias



cdpmin=$2
cdpmax=$3
dcdp=$4
cdp=$cdpmin
rm $FILEOUT
while [ $cdp -le $cdpmax ]
do
       echo "Starting velocity analysis for cdp $cdp"
       echo $cdp
       #suwind < $FILEIN key=sx min=$sx max=$sx count=$fold > panel.$sx
       suwind < $FILEIN key=cdp min=$cdp max=$cdp |  suxwigb key=offset perc=100 xbox=$6 title="cdp=${cdp}"
       suwind < $FILEIN key=cdp min=$cdp max=$cdp >> $FILEOUT

       cdp=`bc -l <<END
		$cdp + $dcdp
END`

done





