#! /bin/sh
# PLOTS 
# Plot for data, primaries and multiples.
# Daniel Trad- UBC Nov 1999
  
FILE=fig1seg2000_data1m.HRT.ps
FILEPS=$FILE'.ps'
FILEJPG=$FILE'.jpg'
# PLot model

FILEN=../work2/data1m


FILE1=$FILEN'.su'
FILE2=$FILEN'.tdi.surad'
FILE3=$FILEN'.tdi.surec'
FILE4=$FILEN'.tdi.sures'

OPTIONPLOT='w'
OPTIONNUM='4'

TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"

LABEL1="time(sec)" 
LABEL2="offset(m)"
LABELR="q(s/m^2)"
LABELD="dV(m^2/s^2)"

case $OPTIONPLOT in
y*)
PLOTR="supswigp f1=0 f2=0 key=f2 label1=$LABEL1 label2=$LABELR"
PLOTI="supswigp f1=0 f2=0 key=offset label1=$LABEL1 label2=$LABELR"
PLOTX="supswigp f1=0 f2=0 key=offset label1=$LABEL1 label2=$LABEL2 perc=99"
GAIN="sugain agc=1 wagc=2"
;;
w*|x*)
PLOTF="supswigp x2beg=-15993 x2end=0 key=offset label1=$LABEL1 label2=$LABELR perc=99"
PLOTR="supswigp key=f2 label1=$LABEL1 label2=$LABELR perc=97"
PLOTX="supswigp key=offset label1=$LABEL1 label2=$LABEL2 perc=100"
PLOTI="supswigp key=offset label1=$LABEL1 label2=$LABELR clip=208"
PLOTD="supswigp key=offset label1=$LABEL1 label2=$LABELD perc=100"
;;
esac


case $OPTIONPLOT in
a*)
#$PLOTM < $FILE1  title=$TITLE1  > p  
$GAIN < $FILE1 | $PLOTX  title=$TITLE1  > p
$GAIN < $FILE2 | $PLOTR perc=99.5  title=$TITLE2  > pp
#$PLOTR < $FILE2  title=$TITLE2  > pp
$GAIN < $FILE3 | $PLOTX  title=$TITLE3  > ppp 
$GAIN < $FILE4 | $PLOTR perc=99.5 title=$TITLE4  > pppp
#$PLOTR < $FILE4  title=$TITLE4  > pppp

;;
x*)
$PLOTX < $FILE1  title=$TITLE1  > p  
$PLOTD < $FILE2  title=$TITLE2  > pp
$PLOTD < $FILE3  title=$TITLE3  > ppp 
$PLOTX < $FILE4  title=$TITLE4  > pppp
;;

w*) # read from workstation and plot in pc
suswapbytes < $FILE1 | $PLOTX  title=$TITLE1  > p  
suswapbytes < $FILE2 | $PLOTR  title=$TITLE2  > pp
suswapbytes < $FILE3 | $PLOTX  title=$TITLE3  > ppp 
suswapbytes < $FILE4 | $PLOTX  title=$TITLE4  > pppp
;;

esac

case $OPTIONNUM in
2*)
psmerge in=p in=pp scale=0.6,0.6 translate=-1,5 translate=4,5 > ~/ps/$FILE
;;
3*)
psmerge in=p in=pp in=ppp  scale=0.42,0.42 translate=0,3 translate=3,3 translate=6,3  > ~/ps/$FILE
;;
4*)
psmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > $HOME'/ps/'$FILE
;;
esac

ghostview $HOME'/ps/'$FILE &











