#! /bin/sh
# PLOTS 
# Plot for data, primaries and multiples.
# Daniel Trad- UBC Nov 1999
  
FILE=fig4seg2000_hyprad.ps

# PLot model

FILEN=cdps2


FILE1=$FILEN'.su'
FILE2=$FILEN'.3iter.surecb'
FILE3=$FILEN'.3iter.surad'
FILE4=$FILEN'.3iter.sures'

OPTIONAGC='n'
OPTIONNUM='3'

TITLE1="(a)"
TITLE2="(b)"
TITLE3="(c)"
TITLE4="(d)"

LABEL1="time(sec)" 
LABEL2="offset(m)"
LABELR="dvel(m/s)"
LABELR1="tau(sec)"

case $OPTIONAGC in
y*)
PLOTR="supswigp f1=0 f2=0 key=f2 label1=$LABEL1 label2=$LABELR"
PLOTI="supswigp f1=0 f2=0 key=offset label1=$LABEL1 label2=$LABELR"
PLOTX="supswigp f1=0 f2=0 key=offset label1=$LABEL1 label2=$LABEL2 perc=99"
GAIN="sugain agc=1 wagc=2"
;;
n*)
PLOTF="supswigp x2beg=-15993 x2end=0 key=offset label1=$LABEL1 label2=$LABELR perc=97"
PLOTR="supswigp f1=0 f2=0 key=offset label1=$LABEL1 label2=$LABELR perc=99"
PLOTX="supswigp key=offset label1=$LABEL1 label2=$LABEL2 perc=97"
PLOTD="supswigp key=offset label1=$LABEL1 label2=$LABEL2 perc=97"
PLOTI="supswigp key=offset label1=$LABEL1 label2=$LABELR perc=97"
;;
esac


case $OPTIONAGC in
y*)
#$PLOTM < $FILE1  title=$TITLE1  > p  
$GAIN < $FILE1 | $PLOTX  title=$TITLE1  > p
$GAIN < $FILE2 | $PLOTR perc=99.5  title=$TITLE2  > pp
#$PLOTR < $FILE2  title=$TITLE2  > pp
$GAIN < $FILE3 | $PLOTX  title=$TITLE3  > ppp 
$GAIN < $FILE4 | $PLOTR perc=99.5 title=$TITLE4  > pppp
#$PLOTR < $FILE4  title=$TITLE4  > pppp

;;
n*)
$PLOTX < $FILE1  title=$TITLE1  > p  
$PLOTX < $FILE2  title=$TITLE2  > pp
$PLOTR < $FILE3  title=$TITLE3  > ppp 
$PLOTF < $FILE4  title=$TITLE4  > pppp
;;
esac

case $OPTIONNUM in
2*)
psmerge in=p in=pp scale=0.6,0.6 translate=-1,5 translate=4,5 > ~/ps/$FILE
;;
3*)
#psmerge in=p in=pp in=ppp  scale=0.42,0.42 translate=0,3 translate=3,3 translate=6,3  > ~/ps/$FILE
psmerge rotate=90 in=p in=pp in=ppp  scale=0.5,0.5 translate=7,0 translate=7,3.5 translate=7,7  > ~/ps/$FILE
;;
4*)
psmerge in=p in=pp in=ppp in=pppp scale=0.5,0.5 translate=0,5 translate=4,5 translate=0,0 translate=4,0 > ~/ps/$FILE
;;
esac

gv ~/ps/$FILE &











