#! /bin/sh
# Template for shells
# Daniel Trad - UBC - CDSST 
set -x

PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=90"


NAME=$1

minoffset=$2
dh=$3

FILEIN=$NAME
FILEOUT=$NAME'.su'



if [ -z ${1} ]; then
    echo "USAGE: Xtemplate file"
    exit 1
fi

ntr=`surange < $FILEIN | sed 1q | sed 's/traces://'`
sushw < $FILEIN key=offset a=$minoffset b=$dh | sushw key=ntr a=$ntr | sugain tpow=1  > $FILEOUT




suxwigb <  $FILEOUT perc=90 key=offset &

