#! /bin/sh
# Run GBmod with Xwindow Graphics
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL Xdemo
#------------------------------------------------

name="sinclinal_ray"
fileout=$name".su"
filestack=$name".stack.su"
modelfile=model.data
rayendsfile=rayends.data
rayfile=rays.data

##### Built syncline model (Figure 14)

trimodel xmin=-1 zmin=0 xmax=5.0 zmax=2.0 maxangle=10 \
1	xedge=-1,0,1,2,3,4,5 \
	zedge=0,0,0,0,0,0,0 \
	sedge=0,0,0,0,0,0,0 \
2       xedge=-1,0,0.5,1.0,1.5,2,2.5,3,4,5 \
        zedge=1,1.1,1.2,1.5,1.7,1.5,1.2,1.1,1,1  \
        sedge=0,0,0,0,0,0,0,0,0,0 \
3	xedge=-1,0,1,2,3,4,5 \
	zedge=2,2,2,2,2,2,2 \
	sedge=0,0,0,0,0,0,0 \
	sfill=1,0.5,0,0,0.25,0,0 \
	sfill=1,1.8,0,0,0.1,0,0 \
	kedge=1,2,3 \
	> $modelfile

sxplot < $modelfile -geom 650x300+670+0 \
        label1="Depth (km)" label2="Distance (km)" \
	tricolor=yellow title="Syncline Model"&


##### Generate Finite-Offset section
set -x
fgrel=100

nangle=130 nxz=401 fangle=-65 langle=65
nt=512 dt=0.004 bw=0 ft=0.0
ng=200
dg=0.01

# dg in meters
dgm=`bc -l <<END
		$dg * 1000
END`

# fsi is the position of the source in meters.
# fs is the postion of the source in km
fsimin=0
fsimax=2000
dfsi=20
fsi=$fsimin
rm $fileout

while [ $fsi -le $fsimax ]
do

# calculate position of source in km
       fs=`bc -l <<END
		$fsi / 1000
END`
    echo $fs
# Final position of the first receiver in km
       fgi=`bc -l <<END
		$fsi + $fgrel
END`
       fg=`bc -l <<END
		$fgi / 1000
END`
    echo $fg

#### create zero offset section
if [ 0 -eq 1 ]; then
triseis <$modelfile  xs=0,4 zs=0,0 xg=0,4 zg=0,0 \
	nangle=$nangle fangle=$fangle langle=$langle \
	kreflect=2 krecord=1 fpeak=25 lscale=0.5 \
	ns=1 fs=$fs ds=0.0 dgds=1 bw=$bw \
        ng=$ng fg=$fg dg=$dg nt=$nt dt=$dt ft=$ft > tempseis

suaddhead ns=$nt < tempseis | sushw key=dt a=4000 | sushw key=sx a=$fsi | sushw key=gx a=$fgi b=$dgm > tempseis2

suchw< tempseis2 key1=offset,cdp key2=gx,gx key3=sx,sx b=1,1 c=-1,1 d=1,2 > tempseis3

else
triray <$modelfile >$rayendsfile xs=$fs zs=0 \
	rayfile=$rayfile krecord=1 nxz=$nxz \
       	nangle=$nangle fangle=$fangle langle=$langle prim=1 \
        refseq=2,1 refseq=1,-1 


xgraph <$rayfile -geom 650x300+650+330 nplot=`cat outpar` n=$nxz \
        x1beg=0 x1end=2 x2beg=-1.0 x2end=5 style=seismic linecolor=7 \
        label1="Depth (km)" label2="Distance (km)" title="Raypaths" &

#### generate and plot commom shot record
gbbeammod <$rayendsfile dg=$dg fg=$fg \
        bw=0 xg=0,4 zg=0,0 ng=$ng lscale=0.5 \
	krecord=1 fpeak=25 nt=$nt dt=$dt ft=0 > temp
fi

suaddhead ns=$nt < temp | sushw key=dt a=4000 | sushw key=sx a=$fsi | sushw key=gx a=$fgi b=$dgm > temp2

suchw< temp2 key1=offset,cdp key2=gx,gx key3=sx,sx b=1,1 c=-1,1 d=1,2 > temp3

cat temp3 >> $fileout

#suxwigb < tempseis3 title=tempseis3 xbox=600 key=gx &
#suxwigb < temp3 title=temp3 key=gx


#xwigb < temp  n1=$nt d1=$dt f1=$ft x1end=2 \
#	n2=$ng f2=0 grid1=none \
# 	perc=100 xcur=1.0 title="common source data" \
# 	hbox=300 wbox=650 xbox=670 ybox=660 \
#	label1="Time (sec)" label2="Offset (km)" &

       fsi=`bc -l <<END
		$fsi + $dfsi
END`

done

#suchw< $fileout key1=offset,cdp key2=gx,gx key3=sx,sx b=1,1 c=-1,1 d=1,2 > temp
#mv temp $fileout

susort +cdp < $fileout > pp; mv pp $fileout
sunmo par=stkvel.sinclinal.su < $fileout | sustack key=cdp > $filestack; 
#Xsetntr $fileout
Xsetntr $filestack
suximage < $filestack &

zap xgraph
zap xwigb
zap sxplot
exit 0


