#! /bin/sh
# Xsuaddh1: converts matalab data from synth0 in sudata
#####################################################################
#######################################################################
# Author: Daniel Trad- March 10/99

set -x 
FILE=../Mod90/tape2
FILEOFF=tape2off
FILEOUT=sutape2
#a2b n1=1 < synth0.dat > pp
a2b n1=1 < tape2off > p
cp p $FILEOFF'b'
suaddhead < $FILE > ppp ns=2500
sushw key=ntr a=135 < ppp > pp
sushw key=offset infile=$FILEOFF'b'  < pp > ppp
sushw key=dt a=500 < ppp > $FILEOUT
suxwigb key=offset wbox=550 hbox=650 < $FILEOUT  &
 
