#! /bin/sh
# Create data from linear velocity models 
#susynlv > data.su nt=251 dt=0.008 nxs=200 dxs=0.05 \
#                  nxo=60 dxo=0.05 fxo=-1.475 ref="1:0,0.25;10,0.25" \
#                  ref="1:0,0.35;5,0.5;10,0.35" ref="1:0,0.75;10,1.0" \
#                  ref="1:0,1.5;10,1.5" v00=1.0 dvdz=2.0 verbose=1 
#                  tmin=0.33

#segyhdrs < data.su 
#segywrite < data.su tape=data.segy 

sushw < data.su key=sx a=130.5 b=0 c=1.0 d=0 j=60 |
sushw key=offset a=-1475 b=50 j=60 |
sushw key=gx a=101 b=1 c=1 d=0 j=60 |
suchw key1=cdp key2=gx key3=sx a=-1 b=1 c=1 |
susort > data.geom.cdp.su cdp offset # CMPs



# Choose some CMPs to perform velocity analysis
suwind < data.geom.cdp.su key=cdp min=290 max=290 > cdp290.su 
suvelan < cdp290.su > semblance290.su fv=500.0 dv=100.0 

suwind < data.geom.cdp.su key=cdp min=390 max=390 > cdp390.su
suvelan < cdp390.su > semblance390.su fv=500.0 dv=100.0 

suwind < data.geom.cdp.su key=cdp min=490 max=490 > cdp490.su 
suvelan < cdp490.su > semblance490.su fv=500.0 dv=100.0 

suwind < data.geom.cdp.su key=cdp min=590 max=590 > cdp590.su
suvelan < cdp590.su  > semblance590.su fv=500.0 dv=100.0 

# NMO to the CMPs using the obtained velocity interpolated models 
sunmo < data.geom.cdp.su cdp=290,390,490,590 vnmo=1250,1500,1800,2400      tnmo=0.47,0.70,1.0,1.45       vnmo=1250,1400,1800,2350,3000  tnmo=0.47,0.57,1.0,1.4,1.57   vnmo=1250,1450,1850,2400       tnmo=0.47,0.68,1.0,1.42       vnmo=1250,1400,1900,2350      tnmo=0.47,0.6,1.07,1.4  >  data.geom.cdp.nmo.su

# Constant offset sections 
susort < data.geom.cdp.nmo.su > data.geom.offset.su offset cdp & 
sudmovz < data.geom.offset.su    cdpmin=230  cdpmax=687  dxcdp=50 noffmix=1 \
vnmo=1250,1500,1800,2400   tnmo=0.47,0.70,1.0,1.45  |
susort  cdp offset > data.geom.cdp.dmo.su

sustack < data.geom.cdp.dmo.su > stack.dmo.su

# Migration using GAZDAG's phase-shift migration 
sugazmig < stack.dmo.su tmig=0.0,2.0 vmig=1000.,5000. dx=25 |
supsimage > stack.dmo.mig.ps \
title="Migrated Stack with true Velocities"

exit 
             






