#! /bin/sh
plotx="suxwigb key=offset perc=97"
set -x
NAME="sx0"

FILE=$NAME".su"
FILEGAP=$NAME"gap.su"
FILEOUT=$NAME"gap.sufk"
FILEGAPNMO=$NAME"gap.sunmo"
FILEOUTNMO=$NAME"gap.sufknmo"
FILEMIX=$NAME"gap.sumix"
FILERES=$NAME"gap.sures"
MODELFILE=$NAME"gap.mig.su"
OPTIONGAP="y"

if [ $OPTIONGAP = 'y' ]; then
    suwind key=offset abs=1 min=1000 < $FILE > $FILEGAP
    Xsetntr  $FILEGAP
    $PLOTX perc=$perc < $FILEGAP &
fi


OFFSETFILE="sx0.suoff"


vmig=9500,10500
tmig=0.1224,6.944

#suinterpfk2 < $FILEGAP  vel=4000 offsetfile=$OFFSETFILE plot=0 itercg=5 iter_end=2 step=1 testadj=1 eps1=0.9 eps2=0.9 modelfile=$MODELFILE > $FILEOUT

suinterpfk3 < $FILEGAP  vmig=$vmig tmig=$tmig offsetfile=$OFFSETFILE plot=0 itercg=2 iter_end=3 step=0.95 testadj=0 eps1=1e-1 eps2=1e-1 modelfile=$MODELFILE ascale=0.6 > $FILEOUT


$plotx < $FILE title=$FILE &
$plotx < $FILEGAP title=$FILEGAP &
$plotx < $FILEOUT title=$FILEOUT &
$plotx < $MODELFILE title=$MODELFILE &

sumixgathers  $FILEGAP $FILEOUT | susort +offset > $FILEMIX

$plotx < $FILEMIX title=$FILEMIX &
suop2 $FILE $FILEMIX > $FILERES 



$plotx < $FILERES title=$FILERES &


