#! /bin/sh
# Xsuinterpmig_ken --- Interpolation of apex shifted hyperbolas  
# by using the non apex centered Radon Transform.
# Data contain multiples of diffractions. 
#
# data preprocessing:
# Althouth the data is a real data set, for this example we need to take a
# window, and make the data to look symmetric 
# from  kencmpsnonmo.su take cdp 5300 and window from 5.5s to end.
# Data name kencmpwin0.su
# then make the data symmetric by 
# suchw key1=offset key2=offset b=-1 < kencmpwin0.su > pp
# cat pp kencmpwin0.su > kencmpwin.su
# sushw key=delrt a=0 < kencmpwin.su > pp
# susort +offset < pp >  kencmpwin.su
# Xsetntr kencmpwin.su
######################################################################
# Author: Daniel Trad- August 2002

# Some shortcuts for plots
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=94"

set -x

METHOD='SOL'
METHOD='TD'
METHOD='TX'
METHOD='FK'
METHOD='PRT'
#METHOD=$1
RADONFORW='y'

sufix=${METHOD}
echo $METHOD

sufix=${METHOD}

FILE=sx50g.su; clip=  #clip corresponding to perc=97

FILEN=$FILE
FILEGAP=$FILE'gap'
FILETEMP=pp
FILETEMP2=ppp

offsetfile=$FILE'off'

FILERAD=${FILEN}'rad'${sufix}
FILERAD2=${FILEN}'rad'${sufix}
FILEREC=$FILEN'rec'${sufix}
FILEREC2=$FILEN'recb'${sufix}
FILEMIX=$FILEN'mix'${sufix}
FILERES=$FILEN'res'${sufix}
FILERESAMP=$FILE'resamp'${sufix}
RESAMPLE='n'
PAR="stkvel.shotsx50.su"
par=$PAR

# Options
SETNTR='y'
GETH='y'
FILT='n'
TAPER='n'
OPTIONGAP='y'

# PASS BAND FILTER
F=1,10,70,80
AMPS=0,1,1,0
# RADON
#***Freq############################ 

VERBOSE=1
fold=1
buffer=10; 
iter_end=4
sinc=0;
parmute=3e-9
parmute=22e-9
nq=90
under=0.999
over=1.001
qmin=-2e-9
factor=1.1
fmax=100

if [ $METHOD = 'TD' ]; then
    eps1=1e-3
    eps2=1e-3
    PROGRAM=suradontd1
    eps=0.01
    dperv=0.03;
    dperv=0.03;
    pervmin=0.5e-9;
    centralq=30
    nq=100
    perc=100
    step=0.9
    itercg=5
    iter_end=3
    smoothf=0
    smoothi=0
    testadj=0
    filtout=0
    restart=1
    LI=1
    t0=0
    clip=63 #clip corresponding to perc=100
    norm=1
    nw=21
    fpeak=25
    nw=0
    dtres=0.008
    ntres=875
elif [ $METHOD = 'TX' ]; then
    eps1=1e-3
    eps2=1e-3
    PROGRAM=suinterptx
    eps=0.01
    dperv=0.03;
    dperv=0.03;
    pervmin=0.5e-9;
    centralq=30
    nq=70
    perc=100
    step=0.9
    itercg=5
    iter_end=1
    smoothf=0
    smoothi=0
    filtout=0
    restart=1
    LI=0
    t0=0
    clip= #clip corresponding to perc=100
    norm=1
    nw=21
    fpeak=25
    nw=0
    dtres=0.008
    ntres=875
elif [ $METHOD = 'FK' ]; then
    eps1=1e-3
    eps2=1e-3
    PROGRAM=suradonfkcube
    eps=0.01
    dperv=0.03;
    dperv=0.03;
    pervmin=0.5e-9;
    centralq=30
    nq=70
    perc=100
    step=0.9
    itercg=5
    iter_end=1
    smoothf=0
    smoothi=0
    filtout=0
    restart=1
    LI=0
    t0=0
    clip= #clip corresponding to perc=100
    norm=1
    nw=21
    fpeak=25
    nw=0
    dtres=0.008
    ntres=875
elif [ $METHOD = 'PRT' ]; then
    PROGRAM=suradonfreq

else 
    PROGRAM=donothing
fi

scale=1.0
CDPMIN=5300
DXCDP=1
CDPMAX=5300

if [ $RADONFORW = 'n' ]; then
    PROGRAM="skipforward"
fi

############################*****
perc=100

cp $FILE $FILETEMP

if [ $OPTIONGAP = 'y' ]; then
#    reject1=-421,-448,-474,-501,-527,-554,-581,421,448,474,501,527,554,581
    reject1=-421,-448,-474,-501,-527,-554,-581,421,448,474,501,527,554,581
    reject2=-2798,-2771,-2744,-2717,-2691,-2664,-2637,-2610,2798,2771,2744,2717,2691,2664,2637,2610

#    reject2=-2878,-2851,-2824,-2798,-2771,-2744,-2717,2878,2851,2824,2798,2771,2744,2717 

#     reject1=-581,-568,-554,-541,-527,-514,-501,-488,-474,-461,-448,-435,-421,-408 

#    reject1=-3786,-3759,-3732,-3706,-3679,-3652,-3625,-3599,-3572,-3545,-3518
    suwind key=offset abs=1 min=0 < $FILETEMP | suwind key=offset abs=1 reject=${reject1},${reject2} > $FILETEMP2  
    #suwind j=2 < $FILETEMP > $FILETEMP2
    #reject=$reject1 accept=$accept1 
    #suwind key=offset j=2   
    Xsetntr  $FILETEMP2
    cp $FILETEMP2 $FILETEMP
    cp $FILETEMP  $FILEGAP

    $PLOTX perc=$perc < $FILETEMP title=$FILETEMP &
    
fi


if [ $SETNTR = 'y' ]; then 
    Xsetntr $FILETEMP
fi

if [ $FILT = 'y' ]; then
    sufilter f=$F amps=$AMPS < $FILETEMP > $FILETEMP2;
    cp  $FILETEMP2 $FILETEMP
fi

# Fill with zero traces and save offset for interpolation
if [ $GETH = 'y' ]; then
    sufill < $FILE | susetntr | sugethw key=offset output=geom  > $offsetfile    
fi

if [ $TAPER = 'y' ]; then
    sutaper < $FILETEMP > $FILETEMP2; cp $FILETEMP2 $FILETEMP
fi

if [ $RESAMPLE = 'y' ]; then
    suresamp < $FILETEMP dt=$dtres nt=$ntres > $FILETEMP2
    cp $FILETEMP2 $FILETEMP
    cp $FILETEMP2 $FILERESAMP
fi


case $PROGRAM in
suradontd1*)
    suradontd1 eps1=$eps1 eps2=$eps2 iter_end=$iter_end itercg=$itercg eps=$eps \
    step=$step  smooth=0 testadj=$testadj verbose=$verbose par=$PAR \
    modelfile=$FILERAD  norm=$norm nw=$nw fpeak=$fpeak centralq=$centralq \
    dperv=$dperv pervmin=$pervmin nq=$nq \
    filtout=$filtout restart=$restart LI=$LI t0=$t0 < $FILETEMP > $FILEREC
;;
suinterptx*)
    dhnew=13.25
    dhnew=27
    sufill < $FILEGAP dhnew=$dhnew |  sufilter amps=1,0 f=80,100 | susetntr > $FILE'zero'
    cp $FILE'zero' $FILETEMP

    suinterptx eps1=9e-1 eps2=9e-1 iter_end=3 itercg=10 eps=1e-3 \
    step=0.97  smooth=0 verbose=1 par="stkvel.shotsx50.su" \
    modelfile=$FILERAD offsetfile=$offsetfile norm=$norm \
    LI=0 t0=0 nw=0 < $FILETEMP > $FILEREC

    sutaperinv $FILE $FILEREC ntaper=50 > $FILEREC'rt'

    sumixgathers $FILEGAP $FILEREC'rt' | susetntr > pppp;
    susort +offset < pppp > $FILE'mix'

    suadapdiff $FILE $FILEREC'rt' > $FILERES'rt'

    
    plotw="suxwigb key=offset x1beg=0 x1end=2 x2beg=-1000 x2end=0 perc=98 perc=98" 
    $plotw < $FILETEMP title=$FILETEMP &
    $plotw < $FILEREC  title=$FILEREC &
    $plotw < $FILE  title=$FILE &


;;
suradonfkcube*)
#   Three options to fill the gaps and interpolate 
#    sushw key=trid a=0 < $FILEGAP > pp;
 #   mv pp $FILEGAP
    sufill < $FILEGAP dhnew=13.25 |  sufilter amps=1,0 f=80,100 | susetntr > $FILE'zero'
#    suinterpm dx=50 < $FILEGAP | sufilter amps=1,0 f=40,60 | susetntr > $FILETEMP
#    sufill < $FILEGAP offset file=kencmp0win.suoff option=1 | susetntr > $FILETEMP
#    sudipfilt < $FILETEMP dx=50  bias=0 amps=0.0,1,0.0 slopes=-0.0003,0,0.0003  > $FILE'zero'  
    cp $FILE'zero' $FILETEMP
    suradonfk0 < $FILETEMP  vmig=1500,1500 tmig=0,4  plot=0 \
    itercg=5 iter_end=3 step=0.95 testadj=0 eps1=9.9999e-1 eps2=9.9999e-1 modelfile=$FILERAD \
    ascale=1 fpeak=20 nw=0 typewav=2 option=3 mute=0  nv=1 dv=1500 lstaper=50 lbtaper=100 Wmthreshold=100 > $FILEREC

# To remove the taper effect, since there is no original uppersampled trace 
# I use a  manufactured trace as follows:
# suinterpm dx=13.25 < sx50gus.su | susetntr > sx50gus_su.su
# sufill dx=13.25  < sx50gus_su.su | susetntr > pp
# mv pp  sx50gus_su.su

    sutaperinv sx50gus_su.su $FILEREC ntaper=50 > $FILEREC'rt'
    sumixgathers $FILEGAP $FILEREC'rt' | susetntr > pppp;
    susort +offset < pppp > $FILE'mix'

    suadapdiff $FILE $FILEREC'rt' > $FILERES'rt'

    
plotw="suxwigb key=offset x1beg=0 x1end=2 x2beg=-1000 x2end=0 perc=98 perc=98" 
    $plotw < $FILETEMP title=$FILETEMP &
    $plotw < $FILEREC  title=$FILEREC &
    $plotw < $FILE  title=$FILE &


;;
suradonfreq*)
    #sutaper < $FILEGAP
    sufill < $FILEGAP dhnew=26.5 |  sufilter amps=1,0 f=80,100 | susetntr > $FILE'zero'
    sugethw key=offset output=geom < $FILE'zero' > $offsetfile

    par=stkvel.sx50g.su
#    par=stkvel.sx50gus.su

    suradonfreq < $FILEGAP  cdpmin=50 cdpmax=50 dxcdp=1 par=$par itercg=25 iter_end=3 solver=cgfft  eps2=9e-1 eps1=9e-1 nq=200 qmin=-3e-8 norm=0 smute=3.0  step=0.95 factor=2 modelfile=$FILERAD  fmax=80 offsetfile=$offsetfile > $FILEREC

    
    suradoninv $FILE'zero' $FILERAD fmax=80 offsetfile=$offsetfile par=$par  nmofactor=1 smute=3.0 > $FILEREC
    
    sutaperinv $FILE $FILEREC ntaper=0 > $FILEREC'rt'
    sumixgathers $FILEGAP $FILEREC'rt' | susetntr > pppp;
    susort +offset < pppp > $FILE'mix'${sufix}

    suadapdiff $FILE $FILEREC'rt' > $FILERES'rt'

    
plotw="suxwigb key=offset x1beg=0 x1end=2 x2beg=-1000 x2end=0 perc=98 perc=98" 
    $plotw < $FILETEMP title=$FILETEMP &
    $plotw < $FILEREC  title=$FILEREC &
    $plotw < $FILE  title=$FILE &


;;


skipforward*)
echo "Skipping forward model.................................."
echo "........................................................"
;;
esac
PLOTXX="suximage perc=98 hbox=900 wbox=700   &"

$PLOTXX < $FILETEMP xbox=0 &
$PLOTXX < $FILEREC xbox=600 &

exit 0


suadapdiff $FILE $FILEREC > $FILERES

sushw key=delrt a=5500 < $FILERES > pp; mv pp $FILERES

$PLOTXX < $FILE xbox=0 x2beg=120 &
$PLOTXX < $FILERES xbox=600 x2beg=120 &


#$PLOTX perc=$perc < $FILERAD title="Radon transform"  perc=97 &
#$PLOTX clip=$clip < $FILEREC title="Reconstructed data from ${PROGRAM} " &

exit 0

susort +offset < $FILEREC | sugain tpow=1 > $FILEREC2
susort +offset < $FILERAD > pp; mv $FILETEMP $FILERAD


sumixgathers  $FILEGAP $FILEREC2 | susort +offset > $FILEMIX
Xsetntr $FILEMIX
suop2 $FILE $FILEMIX op=diff > $FILERES


supswigp < $FILEREC2 perc=99 x1beg=1.85 x1end=4 title=$FILEREC2 | gv - &
supswigp < $FILEMIX perc=99 x1beg=1.85 x1end=4 title=$FILEMIX | gv - &
supswigp < $FILERAD perc=99 x1beg=1.85 x1end=4 title=$FILERAD | gv - &


exit 0  


































