#! /bin/sh
# shell for Kirchhoff modeling for linear v(x,z)
set -x


PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650"

#OPTION='RAD'
OPTION='CSP';output=4
#OPTION='MIG';label="EOM stk0"
#OPTION='KIR';label="Kirchhoff stk0"
#OPTION='LSM';label="LSM stk0"
#OPTION='VEL';label="VEL stk0"

NAME=moddata2n
NAME1=$NAME'.filt.su'
NAME2=$NAME'.csp.su'
PAR=stkvel1.$NAME1

FILE=$NAME'.filt.su'
FILEOUT=$NAME'.eom.su'
FILEOUT2=$NAME'.lsm.su'
FILEOUT3=$NAME'.mig.su'
FILEOUT4=$NAME'.vel.su'
FILECSP=$NAME'.csp.R.su'
FILERAD=$NAME'.rad.su'
FILEREC=$NAME'.rec.su'
FILEOFF=$NAME'.eom.off'
FILECSP1=$NAME'.csp1.su'
FILECSP2=$NAME'.csp2.su'
FILECSP3=$NAME'.csp3.su'
FILECSP4=$NAME'.csp4.su'

CDPMIN=100
CDPMAX=900
dxcdp=10

OUTPUT=1
BETA=60;
TESTHE=1;
PRECISE=0;
HEMIN=-750;
HEMAX=750;
VERBOSE=1
dfold=0.01
buffer=10 
nhcsp=50
smooth=1

# If CSP define limits 
CSPMIN=100
CSPMAX=900
DXCSP=100
###################################

PLOTOPT='XPLOT2'
LABELT="time(sec)" 
LABELO="Offset(m)"

case $OPTION in
MIG*)
sueomig3 < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp  output=1 hemin=$HEMIN hemax=$HEMAX  nhcsp=$nhcsp par=$PAR beta=$BETA testhe=$TESTHE precise=$PRECISE beta=$BETA verbose=$VERBOSE dfold=$dfold smooth=$smooth  > $FILEOUT
#supswigp key=cdp < $FILEOUT | gv - &
$PLOTC < $FILEOUT title=$label &
;;

KIR*)
sukmig3 < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp output=1 par=$PAR verbose=$VERBOSE dfold=$dfold  > $FILEOUT3
#supswigp key=cdp < $FILEOUT | gv - &

$PLOTC < $FILEOUT3  title=$label  &
;;

VEL*)
sueomig3 < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp output=6  beta=$BETA hemin=$HEMIN hemax=$HEMAX nhcsp=$nhcsp par=$PAR itercg=5 iter_end=4 testhe=$TESTHE precise=$PRECISE eps2=1e-3 eps1=1e-3  testadj=0 smooth=0 nq=7 qmin=-150 qmax=150 verbose=$VERBOSE dfold=$dfold buffer=$buffer > $FILEOUT4
#supswigp key=cdp < $FILEOUT | gv - &
$PLOTC < $FILEOUT4  title=$label  &
;;

LSM*)
sueomig3 < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp output=3  beta=$BETA hemin=$HEMIN hemax=$HEMAX nhcsp=$nhcsp par=$PAR itercg=5 iter_end=3 testhe=$TESTHE precise=$PRECISE eps2=1e-3 eps1=1e-3  testadj=0 smooth=$smooth nq=20 qmin=-500 qmax=500 verbose=$VERBOSE dfold=$dfold buffer=$buffer > $FILEOUT2
#supswigp key=cdp < $FILEOUT | gv - &
$PLOTC < $FILEOUT2  title=$label  &
;;


# PLOT CSP gathers

CSP*) 
sueomig3 < $FILE  cdpmin=$CSPMIN cdpmax=$CSPMAX dxcdp=$DXCSP  output=$output verbose=1 hemax=500 hemin=-500 nhcsp=30 par=$PAR itercg=5 iter_end=3 beta=$BETA eps2=1e-3 eps1=1e-3  testadj=0 smooth=0 nq=25 qmin=-500 qmax=500 precise=0 testhe=1  > $FILECSP
;;

# Compute Radon for CSP gathers
RAD*)  
# Save offset  for inverse radon transform
sugethw key=offset output=geom < $FILECSP > $FILEOFF

suradtd method=2 iter_end=2 step=.9 eps=0.01 eps1=1e-3 eps2=1e-3 qmin=-1e-7. qmax=4e-7 nq=32 itercg=10 thres=0.3  < $FILECSP | sufilter  f=5,10,60,70 amps=1,1,1,0  > $FILERAD

supswigp key=f2 < $FILERAD | gv - &

suradtdi offsetfile=$FILEOFF  < $FILERAD | sufilter  f=5,10,60,70 amps=1,1,1,0   > $FILEREC

supswigp key=offset < $FILEREC | gv - &
;;

esac

case $OPTION in
CSP*)
case $PLOTOPT in
    PSPLOT*)
    PLOTPS="supswigp key=offset label1=$LABELT label2=$LABELO perc=100"
    suwind key=cdp min=500  max=500  < $FILECSP | $PLOTPS title="CSP gather for cdp=500"  > $FILECSP'.500.ps' &
    suwind key=cdp min=1000 max=1000 < $FILECSP | $PLOTPS title="CSP gather for cdp=1000" > $FILECSP'.1000.ps' &
    suwind key=cdp min=1500 max=1500 < $FILECSP | $PLOTPS title="CSP gather for cdp=1500" > $FILECSP'.1500.ps' &
    suwind key=cdp min=2000 max=2000 < $FILECSP | $PLOTPS title="CSP gather for cdp=2000" > $FILECSP'.2000.ps' &
    ;;


    XPLOT2*)
    
    csp=$CSPMIN
      
    while [ $csp -le $CSPMAX ]
    do
    title=$csp' CSP'
    suwind key=cdp min=$csp max=$csp  < $FILECSP | $PLOTX  title=$title &

csp=`bc -l <<END
		$csp + $DXCSP
END`

    done
    ;;
esac

;;
esac




 




