#! /bin/sh
# shell for multiple attenuation by RT along a line
# June 16 -2001
# Daniel Trad - UBC

set -x

PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=90"

#NAME=misscn_red_gain_cdp # reduced data set with all cdps
NAME=misscn_gain_cdp # Complete data
#NAME=cdp2800
PAR=stkvel.misscn.su
FILE=$NAME'.su'
FILEOUT=$NAME'.demul.su'

CDPMIN=1000
CDPMAX=1000
dxcdp=2
ntrmax=100000000   # For fast tests.

######################################
# Radon parameters


t0=3;
VERBOSE=1
mute=1        


PLOTOPT='XPLOT3'
LABELT="time(sec)" 
LABELO="Offset(m)"


# Parameters for the center of the line
parmute=5.0e-8
dperv=0.06;
pervmin=1e-9;
centralq=15
nq=55
step=0.95
itercg=10
iter_end=3
filtout=1
restart=1
LI=0
t0=1.5
clip=63 #clip corresponding to perc=100
norm=1
#nw=21
fpeak=25
nw=0

# Testing parameters for the sides of the line
centralq=18
parmute=5e-8
plot=1
outputmodel=1
tm=4.3

suradonlinetd < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=$itercg iter_end=$iter_end eps2=1e-1 eps1=1e-1 nq=$nq verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 t0=$t0 mute=1  parmute=$parmute testadj=$testadj  LI=$LI nw=$nw centralq=$centralq dperv=$dperv pervmin=$pervmin filtout=$filtout restart=$restart  tm=$tm plot=$plot  outputmodel=$outputmodel > $FILEOUT

$PLOTC < $FILEOUT  title=$label  &

################################################################

case $PLOTOPT in
    PSPLOT*)
    ;;

    XPLOT2*)
    
    cdp=$CDPMIN
      
    while [ $cdp -le $CDPMAX ]
    do
    title=$cdp' CDP'
    suwind key=cdp min=$cdp max=$cdp  < $FILEOUT | $PLOTX  title=$title &
    suwind key=cdp min=$cdp max=$cdp  < model.su | $PLOTR  title=$title &

cdp=`bc -l <<END
		$cdp + $DXCDP
END`


    done
    ;;
esac






 




































































































