#! /bin/sh
# shell for multiple attenuation by RT along a line
# June 16 -2001 
# Updated May 1, 2002
# Daniel Trad - UBC

set -x

METHOD="FREQ"


PLOTR="suximage wbox=550 hbox=650 perc=99"
PLOTX="suximage wbox=550 hbox=650 bclip=13.406 wclip=-12.322 "

#NAME=misscn_red_gain_cdp # reduced data set with all cdps
NAME=misscn_1500_1504 # Complete data

PAR=stkvel.misscn.su
FILE=$NAME'.su'
FILEOUT=$NAME'.demul.su'

CDPMIN=1500
CDPMAX=1504
dxcdp=2
ntrmax=100000000   # For fast tests.

######################################
# Radon parameters

t0=1.5;
t0=0;
VERBOSE=1
mute=1        
t0mute=2.6
parmute=1.5e-9

smute=1.6

PLOTOPT='XPLOT3'
LABELT="time(sec)" 
LABELO="Offset(m)"
if [ $METHOD = "FREQ" ]; then

../bin/suradonfreq < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp par=$PAR itercg=30 iter_end=3 eps2=5e-1 eps1=5e-1 nq=150 verbose=$VERBOSE tmpdir='./' t0=$t0 smute=$smute mute=1 parmute=$parmute qmin=-0.25e-8 factor=1.5 solver="$1" t0mute=$t0mute > $FILEOUT
else
# Use other tests here
    exit 0
fi

../su/Xsetntr model.su

$PLOTX < $FILE  title=$FILE  
$PLOTX < $FILEOUT  title=$FILEOUT  
$PLOTR < model.su  title=model.su 

exit 0
################################################################








 




































































































