#! /bin/sh
# shell for multiple attenuation by RT along a line
# June 16 -2001 
# Updated May 1, 2002
# Daniel Trad - UBC

set -x

METHOD="FREQ"

PLOTR="suxwigb key=f2 perc=99.9 "
PLOTX="suxwigb key=offset xbox=600 clip=1 "


NAME=data 
PAR=stkvel.data.su

FILE=$NAME'.su'
FILEOUT=$NAME'.demul.su'

CDPMIN=1
CDPMAX=1
dxcdp=1
ntrmax=100000

######################################
# Radon parameters

t0=0;
VERBOSE=1
mute=1        
t0mute=0
parmute=1e-8
smute=1.6


if [ $METHOD = "FREQ" ]; then
../bin/suradonfreq < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=30 iter_end=10 eps2=1e-2 eps1=1e-2 nq=110 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 buffer=$buffer t0=$t0 smute=$smute mute=$mute  parmute=$parmute qmin=-0.5e-7 factor=0.8 fmax=80 solver="$1" t0mute=$t0mute > $FILEOUT
else
suradonlinetfd < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=$itercg iter_end=3 eps2=8e-1 eps1=8e-1 nq=110 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 buffer=$buffer t0=$t0 smute=$smute mute=1  parmute=1.5e-9 qmin=-0.25e-8 factor=1.5 fmax=80  t0mute=$t0mute stopc=1 typewav=1 > $FILEOUT
fi
$PLOTR < model.su    &
$PLOTX < $FILEOUT    &

################################################################








 




































































































