#! /bin/sh
# shell for multiple attenuation by RT along a line
# June 16 -2001
# Daniel Trad - UBC

set -x

METHOD="STACK"

PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=90"

#NAME=misscn_red_gain_cdp # reduced data set with all cdps
NAME=dataline2 # Complete data

PAR=stkvel.${NAME}.su
FILE=$NAME'.su'
FILEOUT=$NAME'.demul.su'

CDPMIN=1
CDPMAX=3
dxcdp=1
ntrmax=100000000   # For fast tests.

######################################
# Radon parameters

t0=0;
VERBOSE=1
mute=1        
t0mute=3.8
parmute=4.2e-8
parmute=4.2e-8

smute=1.6
tests=2

if [ $tests -eq 0 ]; then
    FILEOUT=$NAME'.fast.su'
elif [ $tests -eq 1 ]; then    
    FILEOUT=$NAME'.demul.su'
elif [ $tests -eq 2 ]; then    
    FILEOUT=$NAME'.stack.su'
fi

PLOTOPT='XPLOT3'
LABELT="time(sec)" 
LABELO="Offset(m)"
if [ $METHOD = "STACK" ]; then
#parmute=1.5e-9
suradonline_stack < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR nq=100 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' smute=$smute mute=1  parmute=$parmute qmin=-0.45e-7 factor=1.5 fmax=60 offsetfile="${NAME}.suoff" tests=$tests eps=0.1 > $FILEOUT
else
itercg=100
suradonlinetfd < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=$itercg iter_end=3 eps2=8e-1 eps1=8e-1 nq=110 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 buffer=$buffer t0=$t0 smute=$smute mute=1  parmute=1.5e-9 qmin=-0.25e-8 factor=1.5 fmax=80  t0mute=$t0mute stopc=1 typewav=1 > $FILEOUT
fi

$PLOTC < $FILEOUT  title=$label  &

################################################################

case $PLOTOPT in
    PSPLOT*)
    ;;

    XPLOT2*)
    
    cdp=$CDPMIN
      
    while [ $cdp -le $CDPMAX ]
    do
    title=$cdp' CDP'
    suwind key=cdp min=$cdp max=$cdp  < $FILEOUT | $PLOTX  title=$title &
    suwind key=cdp min=$cdp max=$cdp  < model.su | $PLOTR  title=$title &

cdp=`bc -l <<END
		$cdp + $DXCDP
END`


    done
    ;;
esac






 




































































































