#! /bin/sh
# shell for multiple attenuation by RT along a line
# June 16 -2001
# Daniel Trad - UBC

set -x

METHOD="${1}"

PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=90"

#NAME=misscn_red_gain_cdp # reduced data set with all cdps
NAME=misscn_gain_cdp # Complete data

PAR=stkvel.misscn.su
FILE=$NAME'.su'
FILEOUT=$NAME'.demul.su'

CDPMIN=1000
CDPMAX=1000
dxcdp=2
ntrmax=100000000   # For fast tests.

######################################
# Radon parameters

t0=1.5;
t0=0;
VERBOSE=1
mute=1        
t0mute=3.8
parmute=1.5e-9
smute=1.6

PLOTOPT='XPLOT3'
LABELT="time(sec)" 
LABELO="Offset(m)"
if [ $METHOD = "SOL" ]; then
#parmute=1.5e-9
suradonline < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=30 iter_end=3 eps2=5e-1 eps1=5e-1 nq=110 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 buffer=$buffer t0=$t0 smute=$smute mute=1  parmute=$parmute qmin=-0.25e-8 factor=1.5 fmax=80 solver="$2" t0mute=$t0mute > $FILEOUT
else
itercg=100
suradonlinetfd < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=$itercg iter_end=3 eps2=8e-1 eps1=8e-1 nq=110 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 buffer=$buffer t0=$t0 smute=$smute mute=1  parmute=1.5e-9 qmin=-0.25e-8 factor=1.5 fmax=80  t0mute=$t0mute stopc=1 typewav=1 > $FILEOUT
fi

$PLOTC < $FILEOUT  title=$label  &

################################################################

case $PLOTOPT in
    PSPLOT*)
    ;;

    XPLOT2*)
    
    cdp=$CDPMIN
      
    while [ $cdp -le $CDPMAX ]
    do
    title=$cdp' CDP'
    suwind key=cdp min=$cdp max=$cdp  < $FILEOUT | $PLOTX  title=$title &
    suwind key=cdp min=$cdp max=$cdp  < model.su | $PLOTR  title=$title &

cdp=`bc -l <<END
		$cdp + $DXCDP
END`


    done
    ;;
esac






 




































































































