#! /bin/sh
# Xsuradonfk_ken --- Attenuation of difractions with  
# non apex centered Radon Transform.
# Data contain multiples of diffractions. 
#
# data preprocessing:
# Althouth the data is a real data set, for this example we need to take a
# window, and make the data to look symmetric 
# from  kencmpsnonmo.su take cdp 5300 and window from 5.5s to end.
# Data name kencmpwin0.su
# then make the data symmetric by 
# suchw key1=offset key2=offset b=-1 < kencmpwin0.su > pp
# cat pp kencmpwin0.su > kencmpwin.su
# sushw key=delrt a=0 < kencmpwin.su > pp
# susort +offset < pp >  kencmpwin.su
# Xsetntr kencmpwin.su
######################################################################
# Author: Daniel Trad- November 2001

# Some shortcuts for plots
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=94"
suxx="suximage perc=98 hbox=900 wbox=700 xbox=$2   curve=curve1 npair=5 & "

set -x

METHOD='TX'
METHOD='RFK' # Radon fk (equiv to LSFK so far)

RADONFORW='y'
OPTIONGAP='y'

sufix=${METHOD}

FILE=data_asym.su; clip=  #clip corresponding to perc=97

FILEN=$FILE
FILEGAP=$FILE'gap'

FILETEMP=pp
FILETEMP2=ppp

offsetfile=$FILE'off'

FILERAD=${FILEN}'rad'${sufix}
FILERAD0=${FILEN}'rad0'${sufix}
FILEREC=$FILEN'rec'${sufix}
FILERES=$FILEN'res'${sufix}

if [ $METHOD = 'TX' ]; then
    PROGRAM=suinterptx
elif [ $METHOD = 'RFK' ]; then
    PROGRAM=suradonfkcube
else 
    PROGRAM=donothing
fi

scale=1.0
CDPMIN=5300
DXCDP=1
CDPMAX=5300

if [ $RADONFORW = 'n' ]; then
    PROGRAM="skipforward"
fi

cp $FILE $FILETEMP

if [ $OPTIONGAP = 'y' ]; then
    #reject1=-2605,-2555,-2505,-2455,-2405,-2355,-2305,-2255,-2205,-2155,-2105
    reject1=-500,-450
    suwind key=offset abs=1 min=60 < $FILETEMP | suwind key=offset reject=$reject1 | susetntr > $FILETEMP2  
    
    cp $FILETEMP2 $FILETEMP
    cp $FILETEMP  $FILEGAP

    $PLOTX perc=$perc < $FILETEMP &
    
fi


############################*****



case $PROGRAM in
suinterptx*)

    mute="tmin_m=0.64 tmax_m=1.44 ihmin_m=35 ihmax_m=48 thres_m=0 slope_m=0"
    #Velocities in stkvel.data_asym2.su
    vel="tnmo=0,0.7,2 vnmo=1800,1900,2550"
    
    sufill  < $FILETEMP > pp1;  # Fill gaps with zero traces 
    #extract offset range with possibly apex locations
    suwind < pp1 key=offset abs=1 max=8000 | sugethw key=offset\
    output=geom > $offsetfile 
    #Use RT to collapse and mute multiples of diffractions
    
    suradontx eps1=9e-1 eps2=9e-1 iter_end=2 itercg=6 eps=1e-3 \
    step=0.97  smooth=0 verbose=1 par="stkvel.data_asym3.su" \
    modelfile=$FILERAD offsetfile=$offsetfile norm=$norm \
    LI=1 t0=0 nw=0 $mute mute=1 < pp1 | suremovedead hmax=800 | susetntr > $FILEREC
    cp migrated2.su $FILERAD0
;;
suradonfkcube*)
    mute="tmin_m=0.64 tmax_m=1.44 ihmin_m=35 ihmax_m=48 thres_m=0 slope_m=0"
    vel="vmig=1950,1950,2100,2700 tmig=0,0.7,1.2,2"
    sufill  < $FILETEMP | susetntr > pp1;  # Fill gaps with zero traces 
   
    # Zero traces are identified with tr.trid=2
    # After suradonfk0 we need remove dead traces and set ntr to the original
    suradonfkcube < pp1 plot=0  $vel \
    itercg=5 iter_end=2 step=0.98 testadj=0 eps1=5.e-1 eps2=5.e-1 \
    modelfile=$FILERAD ascale=1 fpeak=20 nw=0  option=3  \
    $mute mute=0 norm=0 nv=1 > $FILEREC

    cp migrated.su $FILERAD0
;;
skipforward*)
echo "Skipping forward model.................................."
echo "........................................................"
;;
esac
PLOTXX="suximage perc=98 hbox=900 wbox=700 curve=curve1 npair=5  &"

$PLOTXX < $FILERAD xbox=0 &
$PLOTXX < $FILEREC xbox=600 &

suop2 $FILE $FILEREC > $FILERES
#suadapdiff $FILE $FILEREC > $FILERES

#sushw key=delrt a=5500 < $FILERES > pp; mv pp $FILERES

$PLOTXX < $FILE xbox=0  &
$PLOTXX < $FILERES xbox=600 &

# save the migrated data before mute for plot in Xplotsuradonfk_ken
 


exit 0




































