#! /bin/sh
# shell for Radon filtering
# Daniel Trad - UBC
set -x

HBOX=400
WBOX=350
PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650 perc=99"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=99"

OPTION="${1}"

NAME=data2ml
NAME1=$NAME'.su'
NAME2=$NAME'.su'
NAME3=$NAME'.stack.su'
FILE=$NAME'.su'
FILECDP=$NAME'.cdp.su'; 
FILERAD=$NAME'.rad.su'
offsetfile="${NAME}.suoff"
par="stkvel.${NAME}.su"

#if ! [ -f $offsetfile ]; then 
# sugethw key=offset < $NAME1 output=geom  > $offsetfile   
#fi

sugethw key=offset < $NAME1 output=geom  > $offsetfile 
verbose=0
iter_end=2
sinc=0;
nq=100

modelfile="${NAME}.${1}.su"
modelfile2="${NAME}.toep.mute.su"
modelfile="${NAME}.hybrid.iter1.su"
eps1=3e-3
eps2=3e-3

CDPMIN=1
DXCDP=1
CDPMAX=1
nmofactor=1
qmin=-2e-8
factor=4
pseudohyp=0
rtmethod=2
qmin1=1e-4
qmin2=0e-4
#qmin2=-5e-8
factor1=1
factor2=2
rtmethod1=1
rtmethod2=3
depth1=1000
depth2=1000
nq1=0
nq2=100
mute1=1
mute2=0
fmax1=70;
fmax2=70;
amps=1,1,1,1
ffilter=1,55,70,80
factor1=2
factor2=4

fmax1=30;
fmax2=70;
nq=`expr $nq1 + $nq2`
echo "nq=${nq}"


if [ $nmofactor -eq 0 ]; then
    factor2=4
fi

if [ $rtmethod2 -eq 2 ] & [ $OPTION = "hybrid" ] ; then
    pseudohyp=0
    nq=`expr $nq1 + $nq2`
    echo "nq=${nq}"
    qmin2=-2e-8;
fi

if [ $rtmethod -eq 1 ]; then
    echo "Using Pseudo hyperbolic RT "
    qmin=-1e-4
    depth="$2";
    if [ -z "$depth" ]; then
	exit 1
    fi
    factor=4;
fi

###################################

PLOTOPT='XPLOT2'
LABELT="time(sec)" 
LABELO="Offset(m)"

case $OPTION in
HYBRID*|hybrid*)
suradonhybrid < $FILE verbose=$verbose par=$par itercg=25 iter_end=$iter_end eps2=$eps2 eps1=$eps1  testadj=0 smooth=0 nq=$nq  tmpdir='.' norm=0  nmofactor=$nmofactor smute=3.0 step=0.95  modelfile=$modelfile  quantil=0.7  qmin1=$qmin1 qmin2=$qmin2 nq1=$nq1 nq2=$nq2 factor1=$factor1 factor2=$factor2 rtmethod1=$rtmethod1 rtmethod2=$rtmethod2 depth1=$depth1 depth2=$depth2 mute1=$mute1 mute2=$mute2 fmax1=$fmax1 fmax2=$fmax2 amps=$amps ffilter=$ffilter > $FILECDP
;;
TOEP*|toep*)
suradontoep < $FILE verbose=$verbose par=$par  eps1=$eps1   nq=$nq qmin=$qmin tmpdir='.' norm=0 nmofactor=$nmofactor smute=3.0 step=0.95 factor=$factor modelfile=$modelfile  quantil=0.7 depth=$depth  amps=$amps ffilter=$ffilter testvalue=100 > $FILECDP
;;
CGFFT*|cgfft*)
suradoncgfft < $FILE verbose=$verbose par=$par itercg=25 iter_end=$iter_end eps2=$eps2 eps1=$eps1  testadj=0  nq=$nq qmin=$qmin tmpdir='.' norm=0 nmofactor=$nmofactor smute=3.0 step=0.95 factor=$factor modelfile=$modelfile  quantil=0.7 depth=$depth  amps=$amps ffilter=$ffilter > $FILECDP
;;
WTCGLS*|wtcgls*)
suradonwtcgls < $FILE verbose=$verbose par=$par itercg=25 iter_end=$iter_end eps2=$eps2 eps1=$eps1  testadj=0  nq=$nq qmin=$qmin tmpdir='.' norm=0 nmofactor=$nmofactor smute=3.0 step=0.95 factor=$factor modelfile=$modelfile  quantil=0.7 depth=$depth  amps=$amps ffilter=$ffilter > $FILECDP
;;

INV*|inv*)
suradon00inv $FILE $modelfile2 par=$par nq=$nq nmofactor=$nmofactor smute=3.0  pseudohyp=$pseudohyp depth=$depth  amps=$amps ffilter=$ffilter > $FILECDP
;;
BEAM*|beam*)
suradon00inv_beam  $FILE $modelfile par=$par nq=$nq  tmpdir='.'  nmofactor=$nmofactor smute=3.0  pseudohyp=$pseudohyp depth=$depth  qmin1=$qmin1 qmin2=$qmin2 nq1=$nq1 nq2=$nq2 factor1=$factor1 factor2=$factor2 rtmethod1=$rtmethod1 rtmethod2=$rtmethod2 depth1=$depth1 depth2=$depth2 mute1=$mute1 mute2=$mute2 fmax1=$fmax1 fmax2=$fmax2 amps=$amps ffilter=$ffilter > $FILECDP
;;
esac

$PLOTX < $FILECDP perc=99 &
$PLOTR < $modelfile perc=99 &






 






















