#!/bin/sh
# shell for multiple attenuation by RT along a line
# June 16 -2001
# Daniel Trad - UBC

set -x

METHOD="${1}"

PLOTC="suxwigb key=cdp wbox=550 hbox=650"
PLOTR="suxwigb key=f2 wbox=550 hbox=650"
PLOTT="suxwigb wbox=550 hbox=650"
PLOTX="suxwigb key=offset wbox=550 hbox=650 perc=90"

#NAME=misscn_red_gain_cdp # reduced data set with all cdps
NAME=goodf_s35 # Complete data

PAR=stkvel.$NAME.su
FILE=$NAME'.su'
FILEOUT=$NAME'.dgroll.su'

CDPMIN=1
CDPMAX=1
dxcdp=1
ntrmax=100000000   # For fast tests.

######################################
# Radon parameters

t0=1.5;
t0=0;
VERBOSE=1
mute=1        
t0mute=0
parmute=1.5e-5
smute=10

PLOTOPT='XPLOT3'
LABELT="time(sec)" 
LABELO="Offset(m)"
if [ $METHOD = "SOL" ]; then
#parmute=1.5e-9
suradonline < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=30 iter_end=3 eps2=5e-1 eps1=5e-1 nq=250 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 buffer=$buffer t0=$t0 smute=$smute nmofactor=1 mute=0  parmute=$parmute qmin=-15e-8 factor=2 fmax=80 solver="$2" t0mute=$t0mute nmofactor=0 > $FILEOUT
elif [ $METHOD = "TD" ]; then
mute=1
parmute=-6.5e-7 
#qmin=-0.25e-8
t0=1.5
smute=2

centralq=25
suradoneom < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp par=$PAR  itercg=20 iter_end=2 eps2=8e-1 eps1=8e-1 nq=110 verbose=0 ntrmax=$ntrmax norm=0 t0=$t0 smute=$smute mute=$mute  parmute=$parmute qmin=$qmin plot=2 pervmin=0.4e-9 dperv=0 centralq=$centralq LI=0 nw=0 filtout=0  dataprec=5 outputmodel=1 > $FILEOUT

else
itercg=100
suradonlinetfd < $FILE  cdpmin=$CDPMIN cdpmax=$CDPMAX dxcdp=$dxcdp nhcdp=$nhcdp par=$PAR itercg=$itercg iter_end=3 eps2=8e-1 eps1=8e-1 nq=250 verbose=$VERBOSE ntrmax=$ntrmax tmpdir='./' norm=0 buffer=$buffer t0=$t0 smute=$smute mute=0  parmute=15e-5 qmin=-15e-8 factor=2 fmax=80  t0mute=$t0mute stopc=1 nmofactor=0 > $FILEOUT
fi

$PLOTC < $FILEOUT  title=$label  &

################################################################







 




































































































