#! /bin/sh
# Xsuvelan.
######################################################################
# Velocity analisys
#######################################################################
# Author: Daniel Trad- March 10/99


set -x


NV=100
HBOX=400
WBOX=250
MIN=3000
DV=50
MAX=8000
           

FILE=data.su

FILEVEL=$FILE'vel'
sushw key=cdp  < $FILE a=1 | suvelan nv=$NV dv=$DV fv=$MIN |
sushw key=ntr a=$NV |  
suximage  legend=1 f2=$MIN d2=$DV d1=0.02 f1=0 title="Semblanza" mpicks=./vel &
exit 0  






















