#!/bin/sh

set -x

#set header words and filtering
suaddhead < groll.bin ns=512 | sushw key=dt a=4000 | sushw key=offset a=0 b=25 | sufilter  amps=1,0 f=0,30 | sugain tpow=0 |  susetntr > groll.su

#apply mute
sumute < groll.su xmute=100,1900 tmute=0,2.1 > temp1;

suchw  key1=offset key2=offset b=-1  < temp1 | suwind key=offset reject=0 | susort +offset > temp2
cat temp2 temp1 | susetntr | sugain scale=1e5 | susort +offset  > groll0.su

rm temp1 temp2

suxwigb key=offset < groll0.su perc=98 &

# Create the data
susynth2 nh=257 hnear=-3200 dt=0.004 dh=25 shape=3 tau=0.5,1,1.5 vel=3000,3500,4000 fpeak=25 | suaddnoise sn=20 > grolldata.su

# Add groll and data
suop2 grolldata.su groll0.su op=sum > datagroll.su 

# remove one trace and decimate to have power of two
suwind reject=-3200 key=offset < datagroll.su | sufilter f=0,50 amps=1,0 | suresamp dt=0.008 nt=256 > pp
mv pp datagroll.su 

suxwigb key=offset < datagroll.su perc=97 &
