      SUBROUTINE NORM(P,N,PMAX)
!c NORMALIZE P BY MAXIMUM OF ABSOLUTE VALUE OF P
      REAL P(N)
      PMAX=0.
      DO 100 I=1,N
      TST=ABS(P(I))
      IF(PMAX.LT.TST)PMAX=TST
  100 CONTINUE
      DO 200 I=1,N
  200 P(I)=P(I)/PMAX
      RETURN
      END
