#! /bin/sh
# Script to select a shot in a VSP (upgoing), set the depth axis and apply LMO
# Usage: ./Xlmoup offset velocity
# Example: ./Xlmoup.sh 1000 2000
set -x
file1="StraightDAS-INT_Upg_WAVSP.su"
file2="shot_das9_up.su"
file3="shot_das9_up_lmo.su"
offset=$1
vel=$2
dx=25 # DAS sampling interval 25cm, starting at the surface (use vel in cm)
offset2=$offset*100 # offset in cm
suwind < $file1 key=offset min=$offset max=$offset > $file2
sushw < $file2 key=offset a=$offset2 b=$dx > tmp.su
mv tmp.su $file2
sulmo < $file2 linear=-1 vnmo=$vel > $file3
suximage < $file2 title="INPUT" perc=97 &
suximage < $file3 title="LMO" perc=97 xbox=600 &
